// This file is auto-generated by @hey-api/openapi-ts

export interface ClientOptions {
    baseUrl: 'https://registry.scalar.com' | (string & {})
}

/**
 * AdminOrderShipRequest
 *
 * 管理端订单发货请求
 */
export interface AdminOrderShipRequest {
    /**
     * Shipping Sn
     *
     * 快递单号
     */
    shipping_sn: string
}

/**
 * AdminOrderUpdateRequest
 *
 * 管理端订单更新请求（支持收货信息+快递单号）
 */
export interface AdminOrderUpdateRequest {
    /**
     * Shipping Name
     *
     * 收件人姓名
     */
    shipping_name?: string | null
    /**
     * Shipping Phone
     *
     * 收件人电话
     */
    shipping_phone?: string | null
    /**
     * Shipping Address
     *
     * 收件人地址
     */
    shipping_address?: string | null
    /**
     * Shipping Sn
     *
     * 快递单号
     */
    shipping_sn?: string | null
}

/**
 * AdminPlatformPresetCreateRequest
 *
 * 管理端平台预设创建请求
 */
export interface AdminPlatformPresetCreateRequest {
    /**
     * Product Name
     *
     * 商品名称
     */
    product_name: string
    /**
     * Product Description
     *
     * 商品描述
     */
    product_description: string
    /**
     * Product Design
     *
     * 商品设计模板
     */
    product_design: {
        [key: string]: unknown
    }
    /**
     * Product Material Id
     *
     * 商品材料ID
     */
    product_material_id: string
    /**
     * Product Type Id
     *
     * 商品类型ID
     */
    product_type_id: string
}

/**
 * AdminPlatformPresetDetailPublic
 *
 * 管理端平台预设详细信息
 */
export interface AdminPlatformPresetDetailPublic {
    /**
     * Id
     *
     * 预设ID
     */
    id: string
    /**
     * Product Name
     *
     * 商品名称
     */
    product_name: string
    /**
     * Product Description
     *
     * 商品描述
     */
    product_description: string
    /**
     * Product Design
     *
     * 商品设计模板
     */
    product_design: {
        [key: string]: unknown
    }
    /**
     * Product Material Id
     *
     * 商品材料ID
     */
    product_material_id: string
    /**
     * Product Type Id
     *
     * 商品类型ID
     */
    product_type_id: string
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * AdminPlatformPresetUpdateRequest
 *
 * 管理端平台预设更新请求
 */
export interface AdminPlatformPresetUpdateRequest {
    /**
     * Product Name
     *
     * 商品名称
     */
    product_name?: string | null
    /**
     * Product Description
     *
     * 商品描述
     */
    product_description?: string | null
    /**
     * Product Design
     *
     * 商品设计模板
     */
    product_design?: {
        [key: string]: unknown
    } | null
    /**
     * Product Material Id
     *
     * 商品材料ID
     */
    product_material_id?: string | null
    /**
     * Product Type Id
     *
     * 商品类型ID
     */
    product_type_id?: string | null
}

/**
 * AdminPlatformSkuCreateRequest
 *
 * 管理端平台SKU创建请求
 */
export interface AdminPlatformSkuCreateRequest {
    /**
     * Platform
     *
     * 平台标识
     */
    platform: string
    /**
     * Plan Id
     *
     * 平台方案ID
     */
    plan_id: string
    /**
     * Sku Id
     *
     * 平台SKU ID
     */
    sku_id?: string | null
    /**
     * Quantity
     *
     * 每次购买生成的兑换码数量
     */
    quantity?: number
    /**
     * Preset Id
     *
     * 关联预设ID
     */
    preset_id: string
}

/**
 * AdminPlatformSkuPublic
 *
 * 管理端平台SKU信息
 */
export interface AdminPlatformSkuPublic {
    /**
     * Id
     *
     * SKU ID
     */
    id: string
    /**
     * Platform
     *
     * 平台标识
     */
    platform: string
    /**
     * Plan Id
     *
     * 平台方案ID
     */
    plan_id: string
    /**
     * Sku Id
     *
     * 平台SKU ID
     */
    sku_id: string | null
    /**
     * Quantity
     *
     * 每次购买生成的兑换码数量
     */
    quantity: number
    /**
     * Preset Id
     *
     * 关联预设ID
     */
    preset_id: string
    /**
     * 关联预设信息
     */
    preset: PlatformPresetPublic
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * AdminPlatformSkuUpdateRequest
 *
 * 管理端平台SKU更新请求
 */
export interface AdminPlatformSkuUpdateRequest {
    /**
     * Platform
     *
     * 平台标识
     */
    platform?: string | null
    /**
     * Plan Id
     *
     * 平台方案ID
     */
    plan_id?: string | null
    /**
     * Sku Id
     *
     * 平台SKU ID
     */
    sku_id?: string | null
    /**
     * Quantity
     *
     * 每次购买生成的兑换码数量
     */
    quantity?: number | null
    /**
     * Preset Id
     *
     * 关联预设ID
     */
    preset_id?: string | null
}

/**
 * AdminRedemptionPublic
 *
 * 管理端兑换码信息
 */
export interface AdminRedemptionPublic {
    /**
     * Id
     *
     * 兑换码ID
     */
    id: string
    /**
     * Code
     *
     * 兑换码
     */
    code: string
    /**
     * Platform
     *
     * 平台标识
     */
    platform: string
    /**
     * Platform Trade Id
     *
     * 平台交易ID
     */
    platform_trade_id: string
    /**
     * Shipping Name
     *
     * 收件人姓名
     */
    shipping_name: string
    /**
     * Shipping Phone
     *
     * 收件人电话
     */
    shipping_phone: string
    /**
     * Shipping Address
     *
     * 收件人地址
     */
    shipping_address: string
    /**
     * Claimed At
     *
     * 领取时间
     */
    claimed_at: string | null
    /**
     * User Id
     *
     * 领取用户ID
     */
    user_id: string | null
    /**
     * Order Id
     *
     * 关联订单ID
     */
    order_id: string | null
    /**
     * Product Id
     *
     * 关联商品ID
     */
    product_id: string | null
    /**
     * 预设信息
     */
    preset: PlatformPresetPublic
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
}

/**
 * AdminStatsArtifactBreakdown
 *
 * 工件状态分布
 */
export interface AdminStatsArtifactBreakdown {
    /**
     * Failed
     *
     * 失败
     */
    failed?: number
    /**
     * Pending
     *
     * 待定
     */
    pending?: number
    /**
     * In Production
     *
     * 制作中
     */
    in_production?: number
    /**
     * Completed
     *
     * 已完成
     */
    completed?: number
    /**
     * Activated
     *
     * 已激活
     */
    activated?: number
    /**
     * Unassigned
     *
     * 未分配批次
     */
    unassigned?: number
}

/**
 * AdminStatsOrderBreakdown
 *
 * 订单状态分布
 */
export interface AdminStatsOrderBreakdown {
    /**
     * Canceled
     *
     * 已取消
     */
    canceled?: number
    /**
     * Unpaid
     *
     * 待付款
     */
    unpaid?: number
    /**
     * Paid
     *
     * 已付款
     */
    paid?: number
    /**
     * Shipped
     *
     * 已发货
     */
    shipped?: number
    /**
     * Success
     *
     * 已完成
     */
    success?: number
    /**
     * Closed
     *
     * 已关闭
     */
    closed?: number
}

/**
 * AdminStatsResponse
 *
 * 管理端统计信息
 */
export interface AdminStatsResponse {
    /**
     * Total Users
     *
     * 用户总数
     */
    total_users: number
    /**
     * Total Orders
     *
     * 订单总数
     */
    total_orders: number
    /**
     * Total Revenue
     *
     * 总收入（已付款订单）
     */
    total_revenue: string
    /**
     * Total Artifacts
     *
     * 工件总数
     */
    total_artifacts: number
    /**
     * Total Redemptions
     *
     * 兑换码总数
     */
    total_redemptions: number
    /**
     * Unclaimed Redemptions
     *
     * 未领取兑换码数
     */
    unclaimed_redemptions: number
    order_breakdown: AdminStatsOrderBreakdown
    artifact_breakdown: AdminStatsArtifactBreakdown
}

/**
 * AdminUserPermissionUpdateRequest
 *
 * 管理端用户权限更新请求
 */
export interface AdminUserPermissionUpdateRequest {
    /**
     * Permissions
     *
     * 权限节点列表
     */
    permissions: Array<UserPermission>
}

/**
 * AdminUserPublic
 *
 * 管理端用户信息
 */
export interface AdminUserPublic {
    /**
     * Id
     *
     * 用户ID
     */
    id: string
    /**
     * Username
     *
     * 用户名
     */
    username: string
    /**
     * Email
     *
     * 邮箱
     */
    email: string
    /**
     * Permissions
     *
     * 用户权限列表
     */
    permissions: Array<UserPermission>
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * AppResponse[AdminPlatformPresetDetailPublic]
 */
export interface AppResponseAdminPlatformPresetDetailPublic {
    data?: AdminPlatformPresetDetailPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[AdminPlatformSkuPublic]
 */
export interface AppResponseAdminPlatformSkuPublic {
    data?: AdminPlatformSkuPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[AdminStatsResponse]
 */
export interface AppResponseAdminStatsResponse {
    data?: AdminStatsResponse | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[AdminUserPublic]
 */
export interface AppResponseAdminUserPublic {
    data?: AdminUserPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ArtifactManufacturerResponse]
 */
export interface AppResponseArtifactManufacturerResponse {
    data?: LeporidaeApiSchemaArtifactArtifactManufacturerResponse | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ArtifactUserResponse]
 */
export interface AppResponseArtifactUserResponse {
    data?: ArtifactUserResponse | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[BatchPublic]
 */
export interface AppResponseBatchPublic {
    data?: LeporidaeApiSchemaArtifactBatchPublic2 | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ImageAspectPublic]
 */
export interface AppResponseImageAspectPublic {
    data?: ImageAspectPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ImagePublic]
 */
export interface AppResponseImagePublic {
    data?: ImagePublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ImageSearchResponse]
 */
export interface AppResponseImageSearchResponse {
    data?: ImageSearchResponse | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ImageSimplePublic]
 */
export interface AppResponseImageSimplePublic {
    data?: ImageSimplePublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[NoneType]
 */
export interface AppResponseNoneType {
    /**
     * Data
     */
    data?: null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[OrderPublic]
 */
export interface AppResponseOrderPublic {
    data?: OrderPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[OrderSimplePublic]
 */
export interface AppResponseOrderSimplePublic {
    data?: OrderSimplePublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[AdminPlatformPresetDetailPublic]]
 */
export interface AppResponsePageAdminPlatformPresetDetailPublic {
    data?: PageAdminPlatformPresetDetailPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[AdminPlatformSkuPublic]]
 */
export interface AppResponsePageAdminPlatformSkuPublic {
    data?: PageAdminPlatformSkuPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[AdminRedemptionPublic]]
 */
export interface AppResponsePageAdminRedemptionPublic {
    data?: PageAdminRedemptionPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[AdminUserPublic]]
 */
export interface AppResponsePageAdminUserPublic {
    data?: PageAdminUserPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[ArtifactManufacturerResponse]]
 */
export interface AppResponsePageArtifactManufacturerResponse {
    data?: PageArtifactManufacturerResponse | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[BatchPublic]]
 */
export interface AppResponsePageBatchPublic {
    data?: PageBatchPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[OrderPublic]]
 */
export interface AppResponsePageOrderPublic {
    data?: PageOrderPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[ProductPublic]]
 */
export interface AppResponsePageProductPublic {
    data?: PageProductPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[PlatformRedemptionPreviewPublic]
 */
export interface AppResponsePlatformRedemptionPreviewPublic {
    data?: PlatformRedemptionPreviewPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ProductConsultResponse]
 */
export interface AppResponseProductConsultResponse {
    data?: ProductConsultResponse | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ProductPublic]
 */
export interface AppResponseProductPublic {
    data?: LeporidaeApiSchemaProductProductPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[UserPublic]
 */
export interface AppResponseUserPublic {
    data?: UserPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * ArtifactStatus
 */
export type ArtifactStatus = -1 | 0 | 1 | 2 | 3

/**
 * ArtifactStatusUpdateRequest
 *
 * 工件状态更新请求
 */
export interface ArtifactStatusUpdateRequest {
    /**
     * 工件状态
     */
    status: ArtifactStatus
}

/**
 * ArtifactStorageUpdateRequest
 *
 * 工件存储更新请求
 */
export interface ArtifactStorageUpdateRequest {
    /**
     * Storage
     *
     * 工件存储
     */
    storage: {
        [key: string]: unknown
    }
}

/**
 * ArtifactUserResponse
 *
 * 工件用户信息（为用户提供工件元数据）
 */
export interface ArtifactUserResponse {
    /**
     * Id
     *
     * 工件ID
     */
    id: string
    /**
     * Storage
     *
     * 工件内部存储
     */
    storage: {
        [key: string]: unknown
    }
    /**
     * 关联商品
     */
    product: ProductSimpleResponse
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * AuthStrategy
 */
export type AuthStrategy = 0 | 1 | 2

/**
 * BatchAdvanceRequest
 *
 * 批次工件批量推进请求
 */
export interface BatchAdvanceRequest {
    /**
     * Target Status
     *
     * 目标工件状态
     */
    target_status: number
}

/**
 * BatchCreateRequest
 *
 * 批次创建请求
 */
export interface BatchCreateRequest {
    /**
     * Artifact Ids
     *
     * 工件ID列表
     */
    artifact_ids: Array<string>
}

/**
 * BatchUpdateRequest
 *
 * 批次更新请求
 */
export interface BatchUpdateRequest {
    /**
     * Status
     *
     * 批次状态
     */
    status?: number | null
    /**
     * Artifact Ids
     *
     * 工件ID列表
     */
    artifact_ids?: Array<string> | null
}

/**
 * Body_create_image_images_post
 */
export interface BodyCreateImageImagesPost {
    /**
     * File
     *
     * 上传的图片文件
     */
    file: Blob | File
    /**
     * Name
     *
     * 图片名称
     */
    name: string
    /**
     * Description
     *
     * 图片描述
     */
    description: string | null
    /**
     * 图片可见性
     */
    visibility: ImageVisibility
    /**
     * Labels
     *
     * 图片标签列表
     */
    labels: Array<string>
    /**
     * Aspect Id
     *
     * 图片比例ID
     */
    aspect_id: string
}

/**
 * HTTPValidationError
 */
export interface HttpValidationError {
    /**
     * Detail
     */
    detail?: Array<ValidationError>
}

/**
 * ImageAspectPublic
 *
 * 图片比例公开信息
 */
export interface ImageAspectPublic {
    /**
     * Id
     *
     * 比例ID
     */
    id: string
    /**
     * Name
     *
     * 比例名称
     */
    name: string
    /**
     * Description
     *
     * 比例描述
     */
    description: string
    /**
     * Ratio Width Unit
     *
     * 比例宽度
     */
    ratio_width_unit: number
    /**
     * Ratio Height Unit
     *
     * 比例高度
     */
    ratio_height_unit: number
}

/**
 * ImagePublic
 *
 * 图片完整信息（主要用于 Metadata 查询）
 */
export interface ImagePublic {
    /**
     * Id
     *
     * 图片ID
     */
    id: string
    /**
     * Name
     *
     * 图片名称
     */
    name: string
    /**
     * Description
     *
     * 图片描述
     */
    description: string
    /**
     * 图片可见性
     */
    visibility: ImageVisibility
    /**
     * Labels
     *
     * 图片标签列表
     */
    labels: Array<string>
    /**
     * Original Id
     *
     * 图片原始ID
     */
    original_id?: string | null
    /**
     * Original Name
     *
     * 图片原始名称
     */
    original_name?: string | null
    /**
     * User Id
     *
     * 所属用户ID
     */
    user_id: string
    /**
     * Aspect Id
     *
     * 图片比例ID
     */
    aspect_id: string
}

/**
 * ImageSearchResponse
 *
 * 图片搜索响应
 */
export interface ImageSearchResponse {
    /**
     * 图片分页结果
     */
    images: PageImageSimplePublic
    /**
     * Labels
     *
     * 图片标签列表
     */
    labels: Array<string>
}

/**
 * ImageSimplePublic
 *
 * 图片简略信息
 */
export interface ImageSimplePublic {
    /**
     * Id
     *
     * 图片ID
     */
    id: string
    /**
     * Name
     *
     * 图片名称
     */
    name: string
    /**
     * Description
     *
     * 图片描述
     */
    description: string
    /**
     * Labels
     *
     * 图片标签列表
     */
    labels: Array<string>
    /**
     * User Id
     *
     * 所属用户ID
     */
    user_id: string
}

/**
 * ImageUpdateRequest
 *
 * 图片更新请求
 */
export interface ImageUpdateRequest {
    /**
     * Name
     *
     * 图片名称
     */
    name?: string | null
    /**
     * Description
     *
     * 图片描述
     */
    description?: string | null
    /**
     * Visibility
     *
     * 图片可见性
     */
    visibility?: string | null
    /**
     * Labels
     *
     * 图片标签列表
     */
    labels?: Array<string> | null
}

/**
 * ImageVisibility
 */
export type ImageVisibility = -1 | 0 | 1

/**
 * OrderCreateRequest
 *
 * 订单创建请求
 */
export interface OrderCreateRequest {
    /**
     * Items
     *
     * 订单商品列表
     */
    items: Array<OrderItemCreateRequest>
    /**
     * Shipping Name
     *
     * 收件人姓名
     */
    shipping_name: string
    /**
     * Shipping Phone
     *
     * 收件人电话
     */
    shipping_phone: string
    /**
     * Shipping Address
     *
     * 收件人地址
     */
    shipping_address: string
}

/**
 * OrderItemCreateRequest
 *
 * 订单商品项创建请求
 */
export interface OrderItemCreateRequest {
    /**
     * Product Id
     *
     * 商品ID
     */
    product_id: string
    /**
     * Quantity
     *
     * 商品数量
     */
    quantity: number
}

/**
 * OrderItemPublic
 *
 * 订单商品项完整信息（包含商品具体信息）
 */
export interface OrderItemPublic {
    /**
     * Id
     *
     * 订单项ID
     */
    id: string
    /**
     * Quantity
     *
     * 商品数量
     */
    quantity: number
    /**
     * Unit Price
     *
     * 商品单价
     */
    unit_price: string
    /**
     * Total Price
     *
     * 商品总价
     */
    total_price: string
    /**
     * Product Id
     *
     * 商品ID
     */
    product_id: string
    /**
     * 商品信息
     */
    product: LeporidaeApiSchemaProductProductPublic
}

/**
 * OrderPublic
 *
 * 订单完整信息（包含订单商品项具体信息）
 */
export interface OrderPublic {
    /**
     * Id
     *
     * 订单ID
     */
    id: string
    /**
     * 订单状态
     */
    status: OrderStatus
    /**
     * Product Money
     *
     * 商品金额
     */
    product_money: string
    /**
     * Shipping Money
     *
     * 运费金额
     */
    shipping_money: string
    /**
     * Payment Money
     *
     * 支付金额
     */
    payment_money: string
    /**
     * Shipping Name
     *
     * 收件人姓名
     */
    shipping_name: string
    /**
     * Shipping Phone
     *
     * 收件人电话
     */
    shipping_phone: string
    /**
     * Shipping Address
     *
     * 收件人地址
     */
    shipping_address: string
    /**
     * Shipping Sn
     *
     * 快递单号
     */
    shipping_sn: string | null
    /**
     * User Id
     *
     * 所属用户ID
     */
    user_id: string
    /**
     * Paid At
     *
     * 支付时间
     */
    paid_at: string | null
    /**
     * Shipped At
     *
     * 发货时间
     */
    shipped_at: string | null
    /**
     * Closed At
     *
     * 关闭时间
     */
    closed_at: string | null
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
    /**
     * Items
     *
     * 订单商品项列表
     */
    items: Array<OrderItemPublic>
}

/**
 * OrderSimplePublic
 *
 * 订单简略信息
 */
export interface OrderSimplePublic {
    /**
     * Id
     *
     * 订单ID
     */
    id: string
    /**
     * 订单状态
     */
    status: OrderStatus
    /**
     * Product Money
     *
     * 商品金额
     */
    product_money: string
    /**
     * Shipping Money
     *
     * 运费金额
     */
    shipping_money: string
    /**
     * Payment Money
     *
     * 支付金额
     */
    payment_money: string
    /**
     * Shipping Name
     *
     * 收件人姓名
     */
    shipping_name: string
    /**
     * Shipping Phone
     *
     * 收件人电话
     */
    shipping_phone: string
    /**
     * Shipping Address
     *
     * 收件人地址
     */
    shipping_address: string
    /**
     * Shipping Sn
     *
     * 快递单号
     */
    shipping_sn: string | null
    /**
     * User Id
     *
     * 所属用户ID
     */
    user_id: string
    /**
     * Paid At
     *
     * 支付时间
     */
    paid_at: string | null
    /**
     * Shipped At
     *
     * 发货时间
     */
    shipped_at: string | null
    /**
     * Closed At
     *
     * 关闭时间
     */
    closed_at: string | null
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * OrderStatus
 */
export type OrderStatus = -1 | 0 | 1 | 2 | 3 | 4

/**
 * OrderUpdateRequest
 *
 * 订单更新请求
 */
export interface OrderUpdateRequest {
    /**
     * Shipping Name
     *
     * 收件人姓名
     */
    shipping_name?: string | null
    /**
     * Shipping Phone
     *
     * 收件人电话
     */
    shipping_phone?: string | null
    /**
     * Shipping Address
     *
     * 收件人地址
     */
    shipping_address?: string | null
}

/**
 * Page[AdminPlatformPresetDetailPublic]
 */
export interface PageAdminPlatformPresetDetailPublic {
    /**
     * Records
     */
    records: Array<AdminPlatformPresetDetailPublic>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[AdminPlatformSkuPublic]
 */
export interface PageAdminPlatformSkuPublic {
    /**
     * Records
     */
    records: Array<AdminPlatformSkuPublic>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[AdminRedemptionPublic]
 */
export interface PageAdminRedemptionPublic {
    /**
     * Records
     */
    records: Array<AdminRedemptionPublic>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[AdminUserPublic]
 */
export interface PageAdminUserPublic {
    /**
     * Records
     */
    records: Array<AdminUserPublic>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[ArtifactManufacturerResponse]
 */
export interface PageArtifactManufacturerResponse {
    /**
     * Records
     */
    records: Array<LeporidaeApiSchemaArtifactArtifactManufacturerResponse>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[BatchPublic]
 */
export interface PageBatchPublic {
    /**
     * Records
     */
    records: Array<LeporidaeApiSchemaArtifactBatchPublic2>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[ImageSimplePublic]
 */
export interface PageImageSimplePublic {
    /**
     * Records
     */
    records: Array<ImageSimplePublic>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[OrderPublic]
 */
export interface PageOrderPublic {
    /**
     * Records
     */
    records: Array<OrderPublic>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[ProductPublic]
 */
export interface PageProductPublic {
    /**
     * Records
     */
    records: Array<LeporidaeApiSchemaProductProductPublic>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * PlatformPresetPublic
 *
 * 预设公共信息（用于激活页展示）
 */
export interface PlatformPresetPublic {
    /**
     * Id
     *
     * 预设ID
     */
    id: string
    /**
     * Product Name
     *
     * 商品名称
     */
    product_name: string
    /**
     * Product Description
     *
     * 商品描述
     */
    product_description: string
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
}

/**
 * PlatformRedemptionPreviewPublic
 *
 * 兑换码预览信息（用于激活页展示，未领取时返回）
 */
export interface PlatformRedemptionPreviewPublic {
    /**
     * Code
     *
     * 兑换码
     */
    code: string
    /**
     * Platform
     *
     * 平台标识
     */
    platform: string
    /**
     * Shipping Name
     *
     * 收件人姓名
     */
    shipping_name: string
    /**
     * Shipping Phone
     *
     * 收件人电话
     */
    shipping_phone: string
    /**
     * Shipping Address
     *
     * 收件人地址
     */
    shipping_address: string
    /**
     * Claimed At
     *
     * 领取时间（为空表示未领取）
     */
    claimed_at: string | null
    /**
     * Order Id
     *
     * 关联订单ID（领取后回填）
     */
    order_id: string | null
    /**
     * 预设信息
     */
    preset: PlatformPresetPublic
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
}

/**
 * ProductConsultRequest
 *
 * 商品咨询请求
 */
export interface ProductConsultRequest {
    /**
     * Design
     *
     * 商品设计JSON
     */
    design: {
        [key: string]: unknown
    }
    /**
     * Material Id
     *
     * 材料ID
     */
    material_id: string
    /**
     * Type Id
     *
     * 类型ID
     */
    type_id: string
}

/**
 * ProductConsultResponse
 *
 * 商品咨询响应
 */
export interface ProductConsultResponse {
    /**
     * Name
     *
     * 商品名称
     */
    name: string
    /**
     * Description
     *
     * 商品描述
     */
    description: string
    /**
     * Price
     *
     * 商品价格
     */
    price: string
}

/**
 * ProductCreateRequest
 *
 * 商品创建请求
 */
export interface ProductCreateRequest {
    /**
     * Name
     *
     * 商品名称
     */
    name?: string | null
    /**
     * Description
     *
     * 商品描述
     */
    description?: string | null
    /**
     * Design
     *
     * 商品设计JSON
     */
    design: {
        [key: string]: unknown
    }
    /**
     * Material Id
     *
     * 材料ID
     */
    material_id: string
    /**
     * Type Id
     *
     * 类型ID
     */
    type_id: string
}

/**
 * ProductSimpleResponse
 *
 * 商品简要信息
 */
export interface ProductSimpleResponse {
    /**
     * Id
     *
     * 商品ID
     */
    id: string
    /**
     * Design
     *
     * 商品设计JSON
     */
    design: {
        [key: string]: unknown
    }
    /**
     * 商品类型信息
     */
    type: LeporidaeApiSchemaProductProductTypePublic
}

/**
 * ProductUpdateRequest
 *
 * 商品更新请求
 */
export interface ProductUpdateRequest {
    /**
     * Name
     *
     * 商品名称
     */
    name?: string | null
    /**
     * Description
     *
     * 商品描述
     */
    description?: string | null
    /**
     * Design
     *
     * 商品设计JSON
     */
    design?: {
        [key: string]: unknown
    } | null
    /**
     * Material Id
     *
     * 材料ID
     */
    material_id?: string | null
    /**
     * Type Id
     *
     * 类型ID
     */
    type_id?: string | null
}

/**
 * UserAuthRequest
 *
 * 用户登录请求
 */
export interface UserAuthRequest {
    /**
     * Grant Type
     *
     * 授权类型
     */
    grant_type?: 'password' | 'refresh_token'
    /**
     * Username
     *
     * 用户名（仅在 grant_type 为 password 时需要）
     */
    username?: string | null
    /**
     * Password
     *
     * 密码（仅在 grant_type 为 password 时需要）
     */
    password?: string | null
    /**
     * 认证策略（仅在 grant_type 为 password 时需要）
     */
    strategy?: AuthStrategy | null
    /**
     * Refresh Token
     *
     * 刷新令牌（仅在 grant_type 为 refresh_token 时需要）
     */
    refresh_token?: string | null
}

/**
 * UserAuthResponse
 *
 * 用户令牌创建响应
 */
export interface UserAuthResponse {
    /**
     * Access Token
     *
     * 访问令牌
     */
    access_token: string
    /**
     * Refresh Token
     *
     * 刷新令牌
     */
    refresh_token: string
    /**
     * Token Type
     *
     * 令牌类型
     */
    token_type?: string
    /**
     * Expires In
     *
     * 令牌过期时间（秒）
     */
    expires_in: number
}

/**
 * UserCreateRequest
 *
 * 用户注册请求
 */
export interface UserCreateRequest {
    /**
     * Username
     *
     * 用户名
     */
    username: string
    /**
     * Password
     *
     * 密码
     */
    password: string
    /**
     * Email
     *
     * 邮箱
     */
    email: string
}

/**
 * UserMergeRequest
 *
 * 用户合并请求
 */
export interface UserMergeRequest {
    /**
     * Source Access Token
     *
     * 源用户的访问令牌
     */
    source_access_token: string
    /**
     * Target Access Token
     *
     * 目标用户的访问令牌
     */
    target_access_token: string
}

/**
 * UserPermission
 */
export type UserPermission = 'users:admin' | 'images:admin' | 'artifacts:admin' | 'orders:admin' | 'platform:admin'

/**
 * UserPublic
 *
 * 用户公共信息
 */
export interface UserPublic {
    /**
     * Id
     *
     * 用户ID
     */
    id: string
    /**
     * Username
     *
     * 用户名
     */
    username: string
    /**
     * Email
     *
     * 邮箱
     */
    email: string
    /**
     * Permissions
     *
     * 用户权限列表
     */
    permissions: Array<UserPermission>
}

/**
 * UserUpdateRequest
 *
 * 用户更新请求
 */
export interface UserUpdateRequest {
    /**
     * Username
     *
     * 用户名
     */
    username?: string | null
    /**
     * Password
     *
     * 密码
     */
    password?: string | null
    /**
     * Email
     *
     * 邮箱
     */
    email?: string | null
}

/**
 * ValidationError
 */
export interface ValidationError {
    /**
     * Location
     */
    loc: Array<string | number>
    /**
     * Message
     */
    msg: string
    /**
     * Error Type
     */
    type: string
}

/**
 * ArtifactManufacturerResponse
 *
 * 工件制造商信息（为管理员提供完整工件信息）
 */
export interface LeporidaeApiSchemaArtifactArtifactManufacturerResponse {
    /**
     * Id
     *
     * 工件ID
     */
    id: string
    /**
     * Status
     *
     * 工件状态
     */
    status: number
    /**
     * Storage
     *
     * 工件内部存储
     */
    storage: {
        [key: string]: unknown
    }
    /**
     * Batch Id
     *
     * 所属批次ID
     */
    batch_id: string | null
    /**
     * Product Id
     *
     * 所属商品ID
     */
    product_id: string
    /**
     * 关联商品
     */
    product: LeporidaeApiSchemaProductProductPublic2
    /**
     * 关联批次
     */
    batch?: LeporidaeApiSchemaArtifactBatchPublic | null
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * ArtifactManufacturerResponse
 *
 * 工件制造商信息（为管理员提供完整工件信息）
 */
export interface LeporidaeApiSchemaArtifactArtifactManufacturerResponse2 {
    /**
     * Id
     *
     * 工件ID
     */
    id: string
    /**
     * Status
     *
     * 工件状态
     */
    status: number
    /**
     * Storage
     *
     * 工件内部存储
     */
    storage: {
        [key: string]: unknown
    }
    /**
     * Batch Id
     *
     * 所属批次ID
     */
    batch_id: string | null
    /**
     * Product Id
     *
     * 所属商品ID
     */
    product_id: string
    /**
     * 关联商品
     */
    product: LeporidaeApiSchemaProductProductPublic
    /**
     * 关联批次
     */
    batch?: LeporidaeApiSchemaArtifactBatchPublic | null
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * BatchPublic
 *
 * 批次公共信息
 */
export interface LeporidaeApiSchemaArtifactBatchPublic {
    /**
     * Id
     *
     * 批次ID
     */
    id: string
    /**
     * Status
     *
     * 批次状态
     */
    status: number
    /**
     * User Id
     *
     * 创建者用户ID
     */
    user_id: string
    /**
     * Artifacts
     *
     * 工件列表
     */
    artifacts: Array<LeporidaeApiSchemaArtifactArtifactManufacturerResponse>
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * BatchPublic
 *
 * 批次公共信息
 */
export interface LeporidaeApiSchemaArtifactBatchPublic2 {
    /**
     * Id
     *
     * 批次ID
     */
    id: string
    /**
     * Status
     *
     * 批次状态
     */
    status: number
    /**
     * User Id
     *
     * 创建者用户ID
     */
    user_id: string
    /**
     * Artifacts
     *
     * 工件列表
     */
    artifacts: Array<LeporidaeApiSchemaArtifactArtifactManufacturerResponse2>
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * ProductMaterialPublic
 *
 * 材料公共信息
 */
export interface LeporidaeApiSchemaProductProductMaterialPublic {
    /**
     * Id
     *
     * 材料ID
     */
    id: string
    /**
     * Name
     *
     * 材料名称
     */
    name: string
    /**
     * Description
     *
     * 材料描述
     */
    description: string
}

/**
 * ProductPublic
 *
 * 商品公共信息
 */
export interface LeporidaeApiSchemaProductProductPublic {
    /**
     * Id
     *
     * 商品ID
     */
    id: string
    /**
     * Name
     *
     * 商品名称
     */
    name: string
    /**
     * Description
     *
     * 商品描述
     */
    description: string
    /**
     * Price
     *
     * 商品价格
     */
    price: string
    /**
     * Design
     *
     * 商品设计JSON
     */
    design: {
        [key: string]: unknown
    }
    /**
     * Is Modify Allowed
     *
     * 是否允许修改设计
     */
    is_modify_allowed: boolean
    /**
     * User Id
     *
     * 所属用户ID
     */
    user_id: string
    /**
     * 材料信息
     */
    material: LeporidaeApiSchemaProductProductMaterialPublic
    /**
     * 类型信息
     */
    type: LeporidaeApiSchemaProductProductTypePublic
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * ProductPublic
 *
 * 商品公共信息
 */
export interface LeporidaeApiSchemaProductProductPublic2 {
    /**
     * Id
     *
     * 商品ID
     */
    id: string
    /**
     * Name
     *
     * 商品名称
     */
    name: string
    /**
     * Description
     *
     * 商品描述
     */
    description: string
    /**
     * Price
     *
     * 商品价格
     */
    price: string
    /**
     * Design
     *
     * 商品设计JSON
     */
    design: {
        [key: string]: unknown
    }
    /**
     * Is Modify Allowed
     *
     * 是否允许修改设计
     */
    is_modify_allowed: boolean
    /**
     * User Id
     *
     * 所属用户ID
     */
    user_id: string
    /**
     * 材料信息
     */
    material: LeporidaeApiSchemaProductProductMaterialPublic
    /**
     * 类型信息
     */
    type: LeporidaeApiSchemaProductProductTypePublic
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * ProductTypePublic
 *
 * 类型公共信息
 */
export interface LeporidaeApiSchemaProductProductTypePublic {
    /**
     * Id
     *
     * 类型ID
     */
    id: string
    /**
     * Name
     *
     * 类型名称
     */
    name: string
    /**
     * Description
     *
     * 类型描述
     */
    description: string
    /**
     * 商品设计类型
     */
    design_type: LeporidaeInfraModelsProductTypeDesign
    /**
     * Function Types
     *
     * 商品功能类型列表
     */
    function_types: Array<LeporidaeInfraModelsProductTypeFunction>
}

/**
 * ProductTypeDesign
 */
export type LeporidaeInfraModelsProductTypeDesign = 0 | 1

/**
 * ProductTypeFunction
 */
export type LeporidaeInfraModelsProductTypeFunction = 0 | 1

/**
 * UsagiCardDXDesign
 *
 * 兔卡 DX 设计数据
 */
export interface UsagiCardDxDesign {
    /**
     * Game Version
     *
     * 游戏版本
     */
    game_version: string
    /**
     * Simplified Code
     *
     * 卡面标签
     */
    simplified_code: string
    /**
     * Character Name
     *
     * 立绘名称
     */
    character_name: string
    /**
     * Friend Code
     *
     * 好友代码
     */
    friend_code: string
    /**
     * Display Name
     *
     * 玩家名称
     */
    display_name: string
    /**
     * Dx Rating
     *
     * DX 分数
     */
    dx_rating: string
    /**
     * Card Number
     *
     * 卡片编号
     */
    card_number: string
    /**
     * Card Number Label
     *
     * 卡片编号标签内容
     */
    card_number_label: string
    /**
     * Override Qrcode
     *
     * 覆盖二维码内容
     */
    override_qrcode: string
    /**
     * Player Info Color
     *
     * 玩家信息颜色
     */
    player_info_color: string
    /**
     * Chara Info Color
     *
     * 角色信息颜色
     */
    chara_info_color: string
    /**
     * Enable Qrcode Front
     *
     * 启用正面二维码
     */
    enable_qrcode_front: boolean
    /**
     * Enable Qrcode Back
     *
     * 启用反面二维码
     */
    enable_qrcode_back: boolean
    /**
     * Enable Chara Info
     *
     * 启用角色信息
     */
    enable_chara_info: boolean
    /**
     * Enable Landscape
     *
     * 启用横向模式
     */
    enable_landscape: boolean
    /**
     * Enable Mask
     *
     * 启用遮罩
     */
    enable_mask: boolean
    /**
     * Character Id
     *
     * 立绘 ID
     */
    character_id: string
    /**
     * Mask Id
     *
     * 遮罩 ID
     */
    mask_id: string
    /**
     * Background Id
     *
     * 背景 ID
     */
    background_id: string
    /**
     * Cardback Id
     *
     * 卡背 ID
     */
    cardback_id: string
    /**
     * Frame Id
     *
     * 边框 ID
     */
    frame_id: string
    /**
     * Passname Id
     *
     * 通行证 ID
     */
    passname_id: string
}

/**
 * UsagiCardWarsDesign
 *
 * 兔卡 Wars 设计数据
 */
export interface UsagiCardWarsDesign {
    /**
     * Character Name
     *
     * 立绘名称
     */
    character_name: string
    /**
     * Skill Name
     *
     * 技能名称
     */
    skill_name: string
    /**
     * Skill Description
     *
     * 技能描述
     */
    skill_description: string
    /**
     * Miss
     *
     * MISS 值
     */
    miss: number
    /**
     * Combo
     *
     * COMBO 值
     */
    combo: number
    /**
     * Chain
     *
     * CHAIN 值
     */
    chain: number
    /**
     * Character Id
     *
     * 立绘 ID
     */
    character_id: string
    /**
     * Background Id
     *
     * 背景 ID
     */
    background_id: string
    /**
     * Cardback Id
     *
     * 卡背 ID
     */
    cardback_id: string
    /**
     * Frame Id
     *
     * 边框 ID
     */
    frame_id: string
    /**
     * Label Id
     *
     * 标签 ID
     */
    label_id: string
}

/**
 * MaimaiStorage
 *
 * 舞萌存储数据
 */
export interface MaimaiStorage {
    /**
     * Player Name
     *
     * 玩家名称
     */
    player_name?: string | null
    /**
     * Player Rating
     *
     * 玩家评分
     */
    player_rating?: number | null
    /**
     * Friend Code
     *
     * 好友代码
     */
    friend_code?: string | null
    /**
     * Rem Accounts
     *
     * 记住账号列表
     */
    rem_accounts?: Array<{
        /**
         * Label
         *
         * 账号标签
         */
        label: string
        /**
         * MaimaiServer
         */
        server: 'diving_fish' | 'lxns'
        /**
         * Credential
         *
         * 账号鉴权信息
         */
        credential: string
    }>
    /**
     * Updating At
     *
     * 数据更新时间
     */
    updating_at?: string | null
    /**
     * MaimaiUpdatingBehavior
     */
    updating_behavior?: 'adhoc' | 'aggregate'
}

/**
 * UsagiCardStorage
 *
 * 兔卡存储数据
 */
export interface UsagiCardStorage {
    /**
     * Card Title
     *
     * 卡片标题
     */
    card_title?: string | null
    /**
     * Card Avatar
     *
     * 卡片头像
     */
    card_avatar?: string | null
    /**
     * Card Profile
     *
     * 卡片简介
     */
    card_profile?: string | null
    /**
     * Skip Tour
     *
     * 跳过开场引导
     */
    skip_tour?: boolean
    /**
     * Default Function Tab
     *
     * 默认功能菜单标签页
     */
    default_function_tab?: string | null
    /**
     * Default Qbutton Tab
     *
     * 默认快捷菜单标签页
     */
    default_qbutton_tab?: string | null
    /**
     * SecondaryAuthPolicy
     */
    secondary_auth_policy?: 'private' | 'public_read' | 'public_read_write'
    /**
     * Secondary Auth Enabled
     *
     * 启用二级认证
     */
    secondary_auth_enabled?: boolean
    /**
     * Secondary Auth Users
     *
     * 二级认证用户列表
     */
    secondary_auth_users?: Array<string>
    /**
     * Derived From
     *
     * 派生源工件
     */
    derived_from?: string | null
    /**
     * DerivedBehavior
     */
    derived_behavior?: 'none' | 'redirect'
}

export interface RootGetData {
    body?: never
    path?: never
    query?: never
    url: '/'
}

export interface RootGetResponses {
    /**
     * Successful Response
     */
    200: unknown
}

export interface AdminListOrdersAdminOrdersGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Keyword
         *
         * 搜索关键词（收件人/电话/地址/快递单号）
         */
        keyword?: string | null
        /**
         * Status
         *
         * 订单状态
         */
        status?: OrderStatus | null
        /**
         * User Id
         *
         * 用户ID
         */
        user_id?: string | null
    }
    url: '/admin/orders'
}

export interface AdminListOrdersAdminOrdersGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminListOrdersAdminOrdersGetError = AdminListOrdersAdminOrdersGetErrors[keyof AdminListOrdersAdminOrdersGetErrors]

export interface AdminListOrdersAdminOrdersGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageOrderPublic
}

export type AdminListOrdersAdminOrdersGetResponse = AdminListOrdersAdminOrdersGetResponses[keyof AdminListOrdersAdminOrdersGetResponses]

export interface AdminGetOrderAdminOrdersOrderIdGetData {
    body?: never
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/admin/orders/{order_id}'
}

export interface AdminGetOrderAdminOrdersOrderIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminGetOrderAdminOrdersOrderIdGetError = AdminGetOrderAdminOrdersOrderIdGetErrors[keyof AdminGetOrderAdminOrdersOrderIdGetErrors]

export interface AdminGetOrderAdminOrdersOrderIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderPublic
}

export type AdminGetOrderAdminOrdersOrderIdGetResponse = AdminGetOrderAdminOrdersOrderIdGetResponses[keyof AdminGetOrderAdminOrdersOrderIdGetResponses]

export interface AdminUpdateOrderAdminOrdersOrderIdPatchData {
    body: AdminOrderUpdateRequest
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/admin/orders/{order_id}'
}

export interface AdminUpdateOrderAdminOrdersOrderIdPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminUpdateOrderAdminOrdersOrderIdPatchError = AdminUpdateOrderAdminOrdersOrderIdPatchErrors[keyof AdminUpdateOrderAdminOrdersOrderIdPatchErrors]

export interface AdminUpdateOrderAdminOrdersOrderIdPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type AdminUpdateOrderAdminOrdersOrderIdPatchResponse = AdminUpdateOrderAdminOrdersOrderIdPatchResponses[keyof AdminUpdateOrderAdminOrdersOrderIdPatchResponses]

export interface AdminShipOrderAdminOrdersOrderIdShipPostData {
    body: AdminOrderShipRequest
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/admin/orders/{order_id}/ship'
}

export interface AdminShipOrderAdminOrdersOrderIdShipPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminShipOrderAdminOrdersOrderIdShipPostError = AdminShipOrderAdminOrdersOrderIdShipPostErrors[keyof AdminShipOrderAdminOrdersOrderIdShipPostErrors]

export interface AdminShipOrderAdminOrdersOrderIdShipPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type AdminShipOrderAdminOrdersOrderIdShipPostResponse = AdminShipOrderAdminOrdersOrderIdShipPostResponses[keyof AdminShipOrderAdminOrdersOrderIdShipPostResponses]

export interface AdminCancelOrderAdminOrdersOrderIdCancelPostData {
    body?: never
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/admin/orders/{order_id}/cancel'
}

export interface AdminCancelOrderAdminOrdersOrderIdCancelPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminCancelOrderAdminOrdersOrderIdCancelPostError = AdminCancelOrderAdminOrdersOrderIdCancelPostErrors[keyof AdminCancelOrderAdminOrdersOrderIdCancelPostErrors]

export interface AdminCancelOrderAdminOrdersOrderIdCancelPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type AdminCancelOrderAdminOrdersOrderIdCancelPostResponse = AdminCancelOrderAdminOrdersOrderIdCancelPostResponses[keyof AdminCancelOrderAdminOrdersOrderIdCancelPostResponses]

export interface AdminListPresetsAdminPlatformPresetsGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
    }
    url: '/admin/platform/presets'
}

export interface AdminListPresetsAdminPlatformPresetsGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminListPresetsAdminPlatformPresetsGetError = AdminListPresetsAdminPlatformPresetsGetErrors[keyof AdminListPresetsAdminPlatformPresetsGetErrors]

export interface AdminListPresetsAdminPlatformPresetsGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageAdminPlatformPresetDetailPublic
}

export type AdminListPresetsAdminPlatformPresetsGetResponse = AdminListPresetsAdminPlatformPresetsGetResponses[keyof AdminListPresetsAdminPlatformPresetsGetResponses]

export interface AdminCreatePresetAdminPlatformPresetsPostData {
    body: AdminPlatformPresetCreateRequest
    path?: never
    query?: never
    url: '/admin/platform/presets'
}

export interface AdminCreatePresetAdminPlatformPresetsPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminCreatePresetAdminPlatformPresetsPostError = AdminCreatePresetAdminPlatformPresetsPostErrors[keyof AdminCreatePresetAdminPlatformPresetsPostErrors]

export interface AdminCreatePresetAdminPlatformPresetsPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseAdminPlatformPresetDetailPublic
}

export type AdminCreatePresetAdminPlatformPresetsPostResponse = AdminCreatePresetAdminPlatformPresetsPostResponses[keyof AdminCreatePresetAdminPlatformPresetsPostResponses]

export interface AdminDeletePresetAdminPlatformPresetsPresetIdDeleteData {
    body?: never
    path: {
        /**
         * Preset Id
         */
        preset_id: string
    }
    query?: never
    url: '/admin/platform/presets/{preset_id}'
}

export interface AdminDeletePresetAdminPlatformPresetsPresetIdDeleteErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminDeletePresetAdminPlatformPresetsPresetIdDeleteError = AdminDeletePresetAdminPlatformPresetsPresetIdDeleteErrors[keyof AdminDeletePresetAdminPlatformPresetsPresetIdDeleteErrors]

export interface AdminDeletePresetAdminPlatformPresetsPresetIdDeleteResponses {
    /**
     * Successful Response
     */
    200: AppResponseNoneType
}

export type AdminDeletePresetAdminPlatformPresetsPresetIdDeleteResponse = AdminDeletePresetAdminPlatformPresetsPresetIdDeleteResponses[keyof AdminDeletePresetAdminPlatformPresetsPresetIdDeleteResponses]

export interface AdminGetPresetAdminPlatformPresetsPresetIdGetData {
    body?: never
    path: {
        /**
         * Preset Id
         */
        preset_id: string
    }
    query?: never
    url: '/admin/platform/presets/{preset_id}'
}

export interface AdminGetPresetAdminPlatformPresetsPresetIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminGetPresetAdminPlatformPresetsPresetIdGetError = AdminGetPresetAdminPlatformPresetsPresetIdGetErrors[keyof AdminGetPresetAdminPlatformPresetsPresetIdGetErrors]

export interface AdminGetPresetAdminPlatformPresetsPresetIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseAdminPlatformPresetDetailPublic
}

export type AdminGetPresetAdminPlatformPresetsPresetIdGetResponse = AdminGetPresetAdminPlatformPresetsPresetIdGetResponses[keyof AdminGetPresetAdminPlatformPresetsPresetIdGetResponses]

export interface AdminUpdatePresetAdminPlatformPresetsPresetIdPatchData {
    body: AdminPlatformPresetUpdateRequest
    path: {
        /**
         * Preset Id
         */
        preset_id: string
    }
    query?: never
    url: '/admin/platform/presets/{preset_id}'
}

export interface AdminUpdatePresetAdminPlatformPresetsPresetIdPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminUpdatePresetAdminPlatformPresetsPresetIdPatchError = AdminUpdatePresetAdminPlatformPresetsPresetIdPatchErrors[keyof AdminUpdatePresetAdminPlatformPresetsPresetIdPatchErrors]

export interface AdminUpdatePresetAdminPlatformPresetsPresetIdPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseAdminPlatformPresetDetailPublic
}

export type AdminUpdatePresetAdminPlatformPresetsPresetIdPatchResponse = AdminUpdatePresetAdminPlatformPresetsPresetIdPatchResponses[keyof AdminUpdatePresetAdminPlatformPresetsPresetIdPatchResponses]

export interface AdminListSkusAdminPlatformSkusGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
    }
    url: '/admin/platform/skus'
}

export interface AdminListSkusAdminPlatformSkusGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminListSkusAdminPlatformSkusGetError = AdminListSkusAdminPlatformSkusGetErrors[keyof AdminListSkusAdminPlatformSkusGetErrors]

export interface AdminListSkusAdminPlatformSkusGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageAdminPlatformSkuPublic
}

export type AdminListSkusAdminPlatformSkusGetResponse = AdminListSkusAdminPlatformSkusGetResponses[keyof AdminListSkusAdminPlatformSkusGetResponses]

export interface AdminCreateSkuAdminPlatformSkusPostData {
    body: AdminPlatformSkuCreateRequest
    path?: never
    query?: never
    url: '/admin/platform/skus'
}

export interface AdminCreateSkuAdminPlatformSkusPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminCreateSkuAdminPlatformSkusPostError = AdminCreateSkuAdminPlatformSkusPostErrors[keyof AdminCreateSkuAdminPlatformSkusPostErrors]

export interface AdminCreateSkuAdminPlatformSkusPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseAdminPlatformSkuPublic
}

export type AdminCreateSkuAdminPlatformSkusPostResponse = AdminCreateSkuAdminPlatformSkusPostResponses[keyof AdminCreateSkuAdminPlatformSkusPostResponses]

export interface AdminDeleteSkuAdminPlatformSkusSkuIdDeleteData {
    body?: never
    path: {
        /**
         * Sku Id
         */
        sku_id: string
    }
    query?: never
    url: '/admin/platform/skus/{sku_id}'
}

export interface AdminDeleteSkuAdminPlatformSkusSkuIdDeleteErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminDeleteSkuAdminPlatformSkusSkuIdDeleteError = AdminDeleteSkuAdminPlatformSkusSkuIdDeleteErrors[keyof AdminDeleteSkuAdminPlatformSkusSkuIdDeleteErrors]

export interface AdminDeleteSkuAdminPlatformSkusSkuIdDeleteResponses {
    /**
     * Successful Response
     */
    200: AppResponseNoneType
}

export type AdminDeleteSkuAdminPlatformSkusSkuIdDeleteResponse = AdminDeleteSkuAdminPlatformSkusSkuIdDeleteResponses[keyof AdminDeleteSkuAdminPlatformSkusSkuIdDeleteResponses]

export interface AdminUpdateSkuAdminPlatformSkusSkuIdPatchData {
    body: AdminPlatformSkuUpdateRequest
    path: {
        /**
         * Sku Id
         */
        sku_id: string
    }
    query?: never
    url: '/admin/platform/skus/{sku_id}'
}

export interface AdminUpdateSkuAdminPlatformSkusSkuIdPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminUpdateSkuAdminPlatformSkusSkuIdPatchError = AdminUpdateSkuAdminPlatformSkusSkuIdPatchErrors[keyof AdminUpdateSkuAdminPlatformSkusSkuIdPatchErrors]

export interface AdminUpdateSkuAdminPlatformSkusSkuIdPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseAdminPlatformSkuPublic
}

export type AdminUpdateSkuAdminPlatformSkusSkuIdPatchResponse = AdminUpdateSkuAdminPlatformSkusSkuIdPatchResponses[keyof AdminUpdateSkuAdminPlatformSkusSkuIdPatchResponses]

export interface AdminListRedemptionsAdminPlatformRedemptionsGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Claimed
         *
         * 是否已领取（True=已领取, False=未领取, None=全部）
         */
        claimed?: boolean | null
        /**
         * Platform
         *
         * 平台标识
         */
        platform?: string | null
    }
    url: '/admin/platform/redemptions'
}

export interface AdminListRedemptionsAdminPlatformRedemptionsGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminListRedemptionsAdminPlatformRedemptionsGetError = AdminListRedemptionsAdminPlatformRedemptionsGetErrors[keyof AdminListRedemptionsAdminPlatformRedemptionsGetErrors]

export interface AdminListRedemptionsAdminPlatformRedemptionsGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageAdminRedemptionPublic
}

export type AdminListRedemptionsAdminPlatformRedemptionsGetResponse = AdminListRedemptionsAdminPlatformRedemptionsGetResponses[keyof AdminListRedemptionsAdminPlatformRedemptionsGetResponses]

export interface AdminGetStatsAdminStatsGetData {
    body?: never
    path?: never
    query?: never
    url: '/admin/stats'
}

export interface AdminGetStatsAdminStatsGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseAdminStatsResponse
}

export type AdminGetStatsAdminStatsGetResponse = AdminGetStatsAdminStatsGetResponses[keyof AdminGetStatsAdminStatsGetResponses]

export interface AdminListUsersAdminUsersGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Keyword
         *
         * 搜索关键词（用户名/邮箱）
         */
        keyword?: string | null
    }
    url: '/admin/users'
}

export interface AdminListUsersAdminUsersGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminListUsersAdminUsersGetError = AdminListUsersAdminUsersGetErrors[keyof AdminListUsersAdminUsersGetErrors]

export interface AdminListUsersAdminUsersGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageAdminUserPublic
}

export type AdminListUsersAdminUsersGetResponse = AdminListUsersAdminUsersGetResponses[keyof AdminListUsersAdminUsersGetResponses]

export interface AdminGetUserAdminUsersUserIdGetData {
    body?: never
    path: {
        /**
         * User Id
         */
        user_id: string
    }
    query?: never
    url: '/admin/users/{user_id}'
}

export interface AdminGetUserAdminUsersUserIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminGetUserAdminUsersUserIdGetError = AdminGetUserAdminUsersUserIdGetErrors[keyof AdminGetUserAdminUsersUserIdGetErrors]

export interface AdminGetUserAdminUsersUserIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseAdminUserPublic
}

export type AdminGetUserAdminUsersUserIdGetResponse = AdminGetUserAdminUsersUserIdGetResponses[keyof AdminGetUserAdminUsersUserIdGetResponses]

export interface AdminUpdateUserPermissionsAdminUsersUserIdPermissionsPatchData {
    body: AdminUserPermissionUpdateRequest
    path: {
        /**
         * User Id
         */
        user_id: string
    }
    query?: never
    url: '/admin/users/{user_id}/permissions'
}

export interface AdminUpdateUserPermissionsAdminUsersUserIdPermissionsPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdminUpdateUserPermissionsAdminUsersUserIdPermissionsPatchError = AdminUpdateUserPermissionsAdminUsersUserIdPermissionsPatchErrors[keyof AdminUpdateUserPermissionsAdminUsersUserIdPermissionsPatchErrors]

export interface AdminUpdateUserPermissionsAdminUsersUserIdPermissionsPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseAdminUserPublic
}

export type AdminUpdateUserPermissionsAdminUsersUserIdPermissionsPatchResponse = AdminUpdateUserPermissionsAdminUsersUserIdPermissionsPatchResponses[keyof AdminUpdateUserPermissionsAdminUsersUserIdPermissionsPatchResponses]

export interface GetArtifactsArtifactsGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Status
         *
         * 工件状态
         */
        status?: number | null
        /**
         * Product Id
         *
         * 所属商品ID
         */
        product_id?: string | null
        /**
         * Batch Id
         *
         * 所属批次ID
         */
        batch_id?: string | null
    }
    url: '/artifacts'
}

export interface GetArtifactsArtifactsGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetArtifactsArtifactsGetError = GetArtifactsArtifactsGetErrors[keyof GetArtifactsArtifactsGetErrors]

export interface GetArtifactsArtifactsGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageArtifactManufacturerResponse
}

export type GetArtifactsArtifactsGetResponse = GetArtifactsArtifactsGetResponses[keyof GetArtifactsArtifactsGetResponses]

export interface GetArtifactArtifactsArtifactIdGetData {
    body?: never
    path: {
        /**
         * Artifact Id
         */
        artifact_id: string
    }
    query?: never
    url: '/artifacts/{artifact_id}'
}

export interface GetArtifactArtifactsArtifactIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetArtifactArtifactsArtifactIdGetError = GetArtifactArtifactsArtifactIdGetErrors[keyof GetArtifactArtifactsArtifactIdGetErrors]

export interface GetArtifactArtifactsArtifactIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseArtifactUserResponse
}

export type GetArtifactArtifactsArtifactIdGetResponse = GetArtifactArtifactsArtifactIdGetResponses[keyof GetArtifactArtifactsArtifactIdGetResponses]

export interface UpdateArtifactStorageArtifactsArtifactIdStoragePatchData {
    body: ArtifactStorageUpdateRequest
    path: {
        /**
         * Artifact Id
         */
        artifact_id: string
    }
    query?: never
    url: '/artifacts/{artifact_id}/storage'
}

export interface UpdateArtifactStorageArtifactsArtifactIdStoragePatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateArtifactStorageArtifactsArtifactIdStoragePatchError = UpdateArtifactStorageArtifactsArtifactIdStoragePatchErrors[keyof UpdateArtifactStorageArtifactsArtifactIdStoragePatchErrors]

export interface UpdateArtifactStorageArtifactsArtifactIdStoragePatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseArtifactUserResponse
}

export type UpdateArtifactStorageArtifactsArtifactIdStoragePatchResponse = UpdateArtifactStorageArtifactsArtifactIdStoragePatchResponses[keyof UpdateArtifactStorageArtifactsArtifactIdStoragePatchResponses]

export interface UpdateArtifactStatusArtifactsArtifactIdStatusPatchData {
    body: ArtifactStatusUpdateRequest
    path: {
        /**
         * Artifact Id
         */
        artifact_id: string
    }
    query?: never
    url: '/artifacts/{artifact_id}/status'
}

export interface UpdateArtifactStatusArtifactsArtifactIdStatusPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateArtifactStatusArtifactsArtifactIdStatusPatchError = UpdateArtifactStatusArtifactsArtifactIdStatusPatchErrors[keyof UpdateArtifactStatusArtifactsArtifactIdStatusPatchErrors]

export interface UpdateArtifactStatusArtifactsArtifactIdStatusPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseArtifactManufacturerResponse
}

export type UpdateArtifactStatusArtifactsArtifactIdStatusPatchResponse = UpdateArtifactStatusArtifactsArtifactIdStatusPatchResponses[keyof UpdateArtifactStatusArtifactsArtifactIdStatusPatchResponses]

export interface RegisterAuthRegisterPostData {
    body: UserCreateRequest
    path?: never
    query?: never
    url: '/auth/register'
}

export interface RegisterAuthRegisterPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type RegisterAuthRegisterPostError = RegisterAuthRegisterPostErrors[keyof RegisterAuthRegisterPostErrors]

export interface RegisterAuthRegisterPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseUserPublic
}

export type RegisterAuthRegisterPostResponse = RegisterAuthRegisterPostResponses[keyof RegisterAuthRegisterPostResponses]

export interface CreateTokenAuthTokenPostData {
    body: UserAuthRequest
    path?: never
    query?: never
    url: '/auth/token'
}

export interface CreateTokenAuthTokenPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreateTokenAuthTokenPostError = CreateTokenAuthTokenPostErrors[keyof CreateTokenAuthTokenPostErrors]

export interface CreateTokenAuthTokenPostResponses {
    /**
     * Successful Response
     */
    200: UserAuthResponse
}

export type CreateTokenAuthTokenPostResponse = CreateTokenAuthTokenPostResponses[keyof CreateTokenAuthTokenPostResponses]

export interface GetCurrentUserUsersMeGetData {
    body?: never
    path?: never
    query?: never
    url: '/users/me'
}

export interface GetCurrentUserUsersMeGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseUserPublic
}

export type GetCurrentUserUsersMeGetResponse = GetCurrentUserUsersMeGetResponses[keyof GetCurrentUserUsersMeGetResponses]

export interface UpdateCurrentUserUsersMePatchData {
    body: UserUpdateRequest
    path?: never
    query?: never
    url: '/users/me'
}

export interface UpdateCurrentUserUsersMePatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateCurrentUserUsersMePatchError = UpdateCurrentUserUsersMePatchErrors[keyof UpdateCurrentUserUsersMePatchErrors]

export interface UpdateCurrentUserUsersMePatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseUserPublic
}

export type UpdateCurrentUserUsersMePatchResponse = UpdateCurrentUserUsersMePatchResponses[keyof UpdateCurrentUserUsersMePatchResponses]

export interface MergeUsersAuthMergePostData {
    body: UserMergeRequest
    path?: never
    query?: never
    url: '/auth/merge'
}

export interface MergeUsersAuthMergePostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type MergeUsersAuthMergePostError = MergeUsersAuthMergePostErrors[keyof MergeUsersAuthMergePostErrors]

export interface MergeUsersAuthMergePostResponses {
    /**
     * Successful Response
     */
    200: AppResponseNoneType
}

export type MergeUsersAuthMergePostResponse = MergeUsersAuthMergePostResponses[keyof MergeUsersAuthMergePostResponses]

export interface GetBatchesBatchesGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Status
         *
         * 批次状态
         */
        status?: number | null
        /**
         * User Id
         *
         * 创建者用户ID
         */
        user_id?: string | null
    }
    url: '/batches'
}

export interface GetBatchesBatchesGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetBatchesBatchesGetError = GetBatchesBatchesGetErrors[keyof GetBatchesBatchesGetErrors]

export interface GetBatchesBatchesGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageBatchPublic
}

export type GetBatchesBatchesGetResponse = GetBatchesBatchesGetResponses[keyof GetBatchesBatchesGetResponses]

export interface CreateBatchBatchesPostData {
    body: BatchCreateRequest
    path?: never
    query?: never
    url: '/batches'
}

export interface CreateBatchBatchesPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreateBatchBatchesPostError = CreateBatchBatchesPostErrors[keyof CreateBatchBatchesPostErrors]

export interface CreateBatchBatchesPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseBatchPublic
}

export type CreateBatchBatchesPostResponse = CreateBatchBatchesPostResponses[keyof CreateBatchBatchesPostResponses]

export interface GetBatchBatchesBatchIdGetData {
    body?: never
    path: {
        /**
         * Batch Id
         */
        batch_id: string
    }
    query?: never
    url: '/batches/{batch_id}'
}

export interface GetBatchBatchesBatchIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetBatchBatchesBatchIdGetError = GetBatchBatchesBatchIdGetErrors[keyof GetBatchBatchesBatchIdGetErrors]

export interface GetBatchBatchesBatchIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseBatchPublic
}

export type GetBatchBatchesBatchIdGetResponse = GetBatchBatchesBatchIdGetResponses[keyof GetBatchBatchesBatchIdGetResponses]

export interface UpdateBatchBatchesBatchIdPatchData {
    body: BatchUpdateRequest
    path: {
        /**
         * Batch Id
         */
        batch_id: string
    }
    query?: never
    url: '/batches/{batch_id}'
}

export interface UpdateBatchBatchesBatchIdPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateBatchBatchesBatchIdPatchError = UpdateBatchBatchesBatchIdPatchErrors[keyof UpdateBatchBatchesBatchIdPatchErrors]

export interface UpdateBatchBatchesBatchIdPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseBatchPublic
}

export type UpdateBatchBatchesBatchIdPatchResponse = UpdateBatchBatchesBatchIdPatchResponses[keyof UpdateBatchBatchesBatchIdPatchResponses]

export interface AdvanceBatchArtifactsBatchesBatchIdAdvancePostData {
    body: BatchAdvanceRequest
    path: {
        /**
         * Batch Id
         */
        batch_id: string
    }
    query?: never
    url: '/batches/{batch_id}/advance'
}

export interface AdvanceBatchArtifactsBatchesBatchIdAdvancePostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type AdvanceBatchArtifactsBatchesBatchIdAdvancePostError = AdvanceBatchArtifactsBatchesBatchIdAdvancePostErrors[keyof AdvanceBatchArtifactsBatchesBatchIdAdvancePostErrors]

export interface AdvanceBatchArtifactsBatchesBatchIdAdvancePostResponses {
    /**
     * Successful Response
     */
    200: AppResponseBatchPublic
}

export type AdvanceBatchArtifactsBatchesBatchIdAdvancePostResponse = AdvanceBatchArtifactsBatchesBatchIdAdvancePostResponses[keyof AdvanceBatchArtifactsBatchesBatchIdAdvancePostResponses]

export interface GetImagesImagesGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Aspect Id
         *
         * 图片比例ID
         */
        aspect_id?: string | null
        /**
         * Visibility
         *
         * 图片可见性
         */
        visibility?: string | null
        /**
         * Original Id
         *
         * 图片元数据ID
         */
        original_id?: string | null
        /**
         * Labels
         *
         * 图片标签列表
         */
        labels?: Array<string> | null
        /**
         * Keyword
         *
         * 搜索关键词
         */
        keyword?: string | null
    }
    url: '/images'
}

export interface GetImagesImagesGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetImagesImagesGetError = GetImagesImagesGetErrors[keyof GetImagesImagesGetErrors]

export interface GetImagesImagesGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseImageSearchResponse
}

export type GetImagesImagesGetResponse = GetImagesImagesGetResponses[keyof GetImagesImagesGetResponses]

export interface CreateImageImagesPostData {
    body: BodyCreateImageImagesPost
    path?: never
    query?: never
    url: '/images'
}

export interface CreateImageImagesPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreateImageImagesPostError = CreateImageImagesPostErrors[keyof CreateImageImagesPostErrors]

export interface CreateImageImagesPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseImageSimplePublic
}

export type CreateImageImagesPostResponse = CreateImageImagesPostResponses[keyof CreateImageImagesPostResponses]

export interface DeleteImageImagesImageIdDeleteData {
    body?: never
    path: {
        /**
         * Image Id
         */
        image_id: string
    }
    query?: never
    url: '/images/{image_id}'
}

export interface DeleteImageImagesImageIdDeleteErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type DeleteImageImagesImageIdDeleteError = DeleteImageImagesImageIdDeleteErrors[keyof DeleteImageImagesImageIdDeleteErrors]

export interface DeleteImageImagesImageIdDeleteResponses {
    /**
     * Successful Response
     */
    200: AppResponseImageSimplePublic
}

export type DeleteImageImagesImageIdDeleteResponse = DeleteImageImagesImageIdDeleteResponses[keyof DeleteImageImagesImageIdDeleteResponses]

export interface GetImageImagesImageIdGetData {
    body?: never
    path: {
        /**
         * Image Id
         */
        image_id: string
    }
    query?: never
    url: '/images/{image_id}'
}

export interface GetImageImagesImageIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetImageImagesImageIdGetError = GetImageImagesImageIdGetErrors[keyof GetImageImagesImageIdGetErrors]

export interface GetImageImagesImageIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseImagePublic
}

export type GetImageImagesImageIdGetResponse = GetImageImagesImageIdGetResponses[keyof GetImageImagesImageIdGetResponses]

export interface UpdateImageImagesImageIdPatchData {
    body: ImageUpdateRequest
    path: {
        /**
         * Image Id
         */
        image_id: string
    }
    query?: never
    url: '/images/{image_id}'
}

export interface UpdateImageImagesImageIdPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateImageImagesImageIdPatchError = UpdateImageImagesImageIdPatchErrors[keyof UpdateImageImagesImageIdPatchErrors]

export interface UpdateImageImagesImageIdPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseImageSimplePublic
}

export type UpdateImageImagesImageIdPatchResponse = UpdateImageImagesImageIdPatchResponses[keyof UpdateImageImagesImageIdPatchResponses]

export interface GetImageAspectsImagesAspectsAspectIdGetData {
    body?: never
    path: {
        /**
         * Aspect Id
         */
        aspect_id: string
    }
    query?: never
    url: '/images/aspects/{aspect_id}'
}

export interface GetImageAspectsImagesAspectsAspectIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetImageAspectsImagesAspectsAspectIdGetError = GetImageAspectsImagesAspectsAspectIdGetErrors[keyof GetImageAspectsImagesAspectsAspectIdGetErrors]

export interface GetImageAspectsImagesAspectsAspectIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseImageAspectPublic
}

export type GetImageAspectsImagesAspectsAspectIdGetResponse = GetImageAspectsImagesAspectsAspectIdGetResponses[keyof GetImageAspectsImagesAspectsAspectIdGetResponses]

export interface GetOrdersOrdersGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Keyword
         *
         * 搜索关键词
         */
        keyword?: string | null
        /**
         * Status
         *
         * 订单状态
         */
        status?: OrderStatus | null
    }
    url: '/orders'
}

export interface GetOrdersOrdersGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetOrdersOrdersGetError = GetOrdersOrdersGetErrors[keyof GetOrdersOrdersGetErrors]

export interface GetOrdersOrdersGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageOrderPublic
}

export type GetOrdersOrdersGetResponse = GetOrdersOrdersGetResponses[keyof GetOrdersOrdersGetResponses]

export interface CreateOrderOrdersPostData {
    body: OrderCreateRequest
    path?: never
    query?: never
    url: '/orders'
}

export interface CreateOrderOrdersPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreateOrderOrdersPostError = CreateOrderOrdersPostErrors[keyof CreateOrderOrdersPostErrors]

export interface CreateOrderOrdersPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type CreateOrderOrdersPostResponse = CreateOrderOrdersPostResponses[keyof CreateOrderOrdersPostResponses]

export interface GetOrderOrdersOrderIdGetData {
    body?: never
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/orders/{order_id}'
}

export interface GetOrderOrdersOrderIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetOrderOrdersOrderIdGetError = GetOrderOrdersOrderIdGetErrors[keyof GetOrderOrdersOrderIdGetErrors]

export interface GetOrderOrdersOrderIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderPublic
}

export type GetOrderOrdersOrderIdGetResponse = GetOrderOrdersOrderIdGetResponses[keyof GetOrderOrdersOrderIdGetResponses]

export interface UpdateOrderOrdersOrderIdPatchData {
    body: OrderUpdateRequest
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/orders/{order_id}'
}

export interface UpdateOrderOrdersOrderIdPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateOrderOrdersOrderIdPatchError = UpdateOrderOrdersOrderIdPatchErrors[keyof UpdateOrderOrdersOrderIdPatchErrors]

export interface UpdateOrderOrdersOrderIdPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type UpdateOrderOrdersOrderIdPatchResponse = UpdateOrderOrdersOrderIdPatchResponses[keyof UpdateOrderOrdersOrderIdPatchResponses]

export interface CancelOrderOrdersOrderIdCancelPostData {
    body?: never
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/orders/{order_id}/cancel'
}

export interface CancelOrderOrdersOrderIdCancelPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CancelOrderOrdersOrderIdCancelPostError = CancelOrderOrdersOrderIdCancelPostErrors[keyof CancelOrderOrdersOrderIdCancelPostErrors]

export interface CancelOrderOrdersOrderIdCancelPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type CancelOrderOrdersOrderIdCancelPostResponse = CancelOrderOrdersOrderIdCancelPostResponses[keyof CancelOrderOrdersOrderIdCancelPostResponses]

export interface PayOrderOrdersOrderIdPayPostData {
    body?: never
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/orders/{order_id}/pay'
}

export interface PayOrderOrdersOrderIdPayPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type PayOrderOrdersOrderIdPayPostError = PayOrderOrdersOrderIdPayPostErrors[keyof PayOrderOrdersOrderIdPayPostErrors]

export interface PayOrderOrdersOrderIdPayPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type PayOrderOrdersOrderIdPayPostResponse = PayOrderOrdersOrderIdPayPostResponses[keyof PayOrderOrdersOrderIdPayPostResponses]

export interface GetProductsProductsGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Keyword
         *
         * 搜索关键词
         */
        keyword?: string | null
        /**
         * User Id
         *
         * 所属用户ID
         */
        user_id?: string | null
        /**
         * Material Id
         *
         * 材料ID
         */
        material_id?: string | null
        /**
         * Type Id
         *
         * 类型ID
         */
        type_id?: string | null
    }
    url: '/products'
}

export interface GetProductsProductsGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetProductsProductsGetError = GetProductsProductsGetErrors[keyof GetProductsProductsGetErrors]

export interface GetProductsProductsGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageProductPublic
}

export type GetProductsProductsGetResponse = GetProductsProductsGetResponses[keyof GetProductsProductsGetResponses]

export interface CreateProductProductsPostData {
    body: ProductCreateRequest
    path?: never
    query?: never
    url: '/products'
}

export interface CreateProductProductsPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreateProductProductsPostError = CreateProductProductsPostErrors[keyof CreateProductProductsPostErrors]

export interface CreateProductProductsPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseProductPublic
}

export type CreateProductProductsPostResponse = CreateProductProductsPostResponses[keyof CreateProductProductsPostResponses]

export interface GetProductProductsProductIdGetData {
    body?: never
    path: {
        /**
         * Product Id
         */
        product_id: string
    }
    query?: never
    url: '/products/{product_id}'
}

export interface GetProductProductsProductIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetProductProductsProductIdGetError = GetProductProductsProductIdGetErrors[keyof GetProductProductsProductIdGetErrors]

export interface GetProductProductsProductIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseProductPublic
}

export type GetProductProductsProductIdGetResponse = GetProductProductsProductIdGetResponses[keyof GetProductProductsProductIdGetResponses]

export interface UpdateProductProductsProductIdPatchData {
    body: ProductUpdateRequest
    path: {
        /**
         * Product Id
         */
        product_id: string
    }
    query?: never
    url: '/products/{product_id}'
}

export interface UpdateProductProductsProductIdPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateProductProductsProductIdPatchError = UpdateProductProductsProductIdPatchErrors[keyof UpdateProductProductsProductIdPatchErrors]

export interface UpdateProductProductsProductIdPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseProductPublic
}

export type UpdateProductProductsProductIdPatchResponse = UpdateProductProductsProductIdPatchResponses[keyof UpdateProductProductsProductIdPatchResponses]

export interface ConsultProductProductsConsultPostData {
    body: ProductConsultRequest
    path?: never
    query?: never
    url: '/products/consult'
}

export interface ConsultProductProductsConsultPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type ConsultProductProductsConsultPostError = ConsultProductProductsConsultPostErrors[keyof ConsultProductProductsConsultPostErrors]

export interface ConsultProductProductsConsultPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseProductConsultResponse
}

export type ConsultProductProductsConsultPostResponse = ConsultProductProductsConsultPostResponses[keyof ConsultProductProductsConsultPostResponses]

export interface GetRedemptionRedemptionsCodeGetData {
    body?: never
    path: {
        /**
         * Code
         *
         * 兑换码
         */
        code: string
    }
    query?: never
    url: '/redemptions/{code}'
}

export interface GetRedemptionRedemptionsCodeGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetRedemptionRedemptionsCodeGetError = GetRedemptionRedemptionsCodeGetErrors[keyof GetRedemptionRedemptionsCodeGetErrors]

export interface GetRedemptionRedemptionsCodeGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePlatformRedemptionPreviewPublic
}

export type GetRedemptionRedemptionsCodeGetResponse = GetRedemptionRedemptionsCodeGetResponses[keyof GetRedemptionRedemptionsCodeGetResponses]

export interface ClaimRedemptionRedemptionsCodeClaimPostData {
    body?: never
    path: {
        /**
         * Code
         *
         * 兑换码
         */
        code: string
    }
    query?: never
    url: '/redemptions/{code}/claim'
}

export interface ClaimRedemptionRedemptionsCodeClaimPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type ClaimRedemptionRedemptionsCodeClaimPostError = ClaimRedemptionRedemptionsCodeClaimPostErrors[keyof ClaimRedemptionRedemptionsCodeClaimPostErrors]

export interface ClaimRedemptionRedemptionsCodeClaimPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type ClaimRedemptionRedemptionsCodeClaimPostResponse = ClaimRedemptionRedemptionsCodeClaimPostResponses[keyof ClaimRedemptionRedemptionsCodeClaimPostResponses]
