// This file is auto-generated by @hey-api/openapi-ts

export interface ClientOptions {
    baseUrl: 'https://registry.scalar.com' | (string & {})
}

/**
 * AppResponse[ArtifactManufacturerResponse]
 */
export interface AppResponseArtifactManufacturerResponse {
    data?: ArtifactManufacturerResponse | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ArtifactUserResponse]
 */
export interface AppResponseArtifactUserResponse {
    data?: ArtifactUserResponse | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[BatchPublic]
 */
export interface AppResponseBatchPublic {
    data?: BatchPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ImageAspectPublic]
 */
export interface AppResponseImageAspectPublic {
    data?: ImageAspectPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ImagePublic]
 */
export interface AppResponseImagePublic {
    data?: ImagePublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ImageSearchResponse]
 */
export interface AppResponseImageSearchResponse {
    data?: ImageSearchResponse | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ImageSimplePublic]
 */
export interface AppResponseImageSimplePublic {
    data?: ImageSimplePublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[NoneType]
 */
export interface AppResponseNoneType {
    /**
     * Data
     */
    data?: null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[OrderPublic]
 */
export interface AppResponseOrderPublic {
    data?: OrderPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[OrderSimplePublic]
 */
export interface AppResponseOrderSimplePublic {
    data?: OrderSimplePublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[ArtifactManufacturerResponse]]
 */
export interface AppResponsePageArtifactManufacturerResponse {
    data?: PageArtifactManufacturerResponse | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[BatchPublic]]
 */
export interface AppResponsePageBatchPublic {
    data?: PageBatchPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[OrderPublic]]
 */
export interface AppResponsePageOrderPublic {
    data?: PageOrderPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[Page[ProductPublic]]
 */
export interface AppResponsePageProductPublic {
    data?: PageProductPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ProductConsultResponse]
 */
export interface AppResponseProductConsultResponse {
    data?: ProductConsultResponse | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[ProductPublic]
 */
export interface AppResponseProductPublic {
    data?: ProductPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * AppResponse[UserPublic]
 */
export interface AppResponseUserPublic {
    data?: UserPublic | null
    /**
     * Code
     */
    code?: number
    /**
     * Message
     */
    message?: string
    /**
     * Timestamp
     */
    timestamp?: string
}

/**
 * ArtifactManufacturerResponse
 *
 * 工件制造商信息（为管理员提供完整工件信息）
 */
export interface ArtifactManufacturerResponse {
    /**
     * Id
     *
     * 工件ID
     */
    id: string
    /**
     * Status
     *
     * 工件状态
     */
    status: number
    /**
     * Storage
     *
     * 工件内部存储
     */
    storage: {
        [key: string]: unknown
    }
    /**
     * Batch Id
     *
     * 所属批次ID
     */
    batch_id: string | null
    /**
     * Product Id
     *
     * 所属商品ID
     */
    product_id: string
    /**
     * 关联商品
     */
    product: ProductPublic
    /**
     * 关联批次
     */
    batch?: BatchPublic | null
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * ArtifactStatus
 */
export type ArtifactStatus = -1 | 0 | 1 | 2 | 3

/**
 * ArtifactStatusUpdateRequest
 *
 * 工件状态更新请求
 */
export interface ArtifactStatusUpdateRequest {
    /**
     * 工件状态
     */
    status: ArtifactStatus
}

/**
 * ArtifactStorageUpdateRequest
 *
 * 工件存储更新请求
 */
export interface ArtifactStorageUpdateRequest {
    /**
     * Storage
     *
     * 工件存储
     */
    storage: {
        [key: string]: unknown
    }
}

/**
 * ArtifactUserResponse
 *
 * 工件用户信息（为用户提供工件元数据）
 */
export interface ArtifactUserResponse {
    /**
     * Id
     *
     * 工件ID
     */
    id: string
    /**
     * Storage
     *
     * 工件内部存储
     */
    storage: {
        [key: string]: unknown
    }
    /**
     * 关联商品
     */
    product: ProductSimpleResponse
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * AuthStrategy
 */
export type AuthStrategy = 0 | 1 | 2

/**
 * BatchCreateRequest
 *
 * 批次创建请求
 */
export interface BatchCreateRequest {
    /**
     * Artifact Ids
     *
     * 工件ID列表
     */
    artifact_ids: Array<string>
}

/**
 * BatchPublic
 *
 * 批次公共信息
 */
export interface BatchPublic {
    /**
     * Id
     *
     * 批次ID
     */
    id: string
    /**
     * Status
     *
     * 批次状态
     */
    status: number
    /**
     * User Id
     *
     * 创建者用户ID
     */
    user_id: string
    /**
     * Artifacts
     *
     * 工件列表
     */
    artifacts: Array<ArtifactManufacturerResponse>
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * BatchUpdateRequest
 *
 * 批次更新请求
 */
export interface BatchUpdateRequest {
    /**
     * Status
     *
     * 批次状态
     */
    status?: number | null
    /**
     * Artifact Ids
     *
     * 工件ID列表
     */
    artifact_ids?: Array<string> | null
}

/**
 * Body_create_image_images_post
 */
export interface BodyCreateImageImagesPost {
    /**
     * File
     *
     * 上传的图片文件
     */
    file: Blob | File
    /**
     * Name
     *
     * 图片名称
     */
    name: string
    /**
     * Description
     *
     * 图片描述
     */
    description: string | null
    /**
     * 图片可见性
     */
    visibility: ImageVisibility
    /**
     * Labels
     *
     * 图片标签列表
     */
    labels: Array<string>
    /**
     * Aspect Id
     *
     * 图片比例ID
     */
    aspect_id: string
}

/**
 * HTTPValidationError
 */
export interface HttpValidationError {
    /**
     * Detail
     */
    detail?: Array<ValidationError>
}

/**
 * ImageAspectPublic
 *
 * 图片比例公开信息
 */
export interface ImageAspectPublic {
    /**
     * Id
     *
     * 比例ID
     */
    id: string
    /**
     * Name
     *
     * 比例名称
     */
    name: string
    /**
     * Description
     *
     * 比例描述
     */
    description: string
    /**
     * Ratio Width Unit
     *
     * 比例宽度
     */
    ratio_width_unit: number
    /**
     * Ratio Height Unit
     *
     * 比例高度
     */
    ratio_height_unit: number
}

/**
 * ImagePublic
 *
 * 图片完整信息（主要用于 Metadata 查询）
 */
export interface ImagePublic {
    /**
     * Id
     *
     * 图片ID
     */
    id: string
    /**
     * Name
     *
     * 图片名称
     */
    name: string
    /**
     * Description
     *
     * 图片描述
     */
    description: string
    /**
     * 图片可见性
     */
    visibility: ImageVisibility
    /**
     * Labels
     *
     * 图片标签列表
     */
    labels: Array<string>
    /**
     * Original Id
     *
     * 图片原始ID
     */
    original_id?: string | null
    /**
     * Original Name
     *
     * 图片原始名称
     */
    original_name?: string | null
    /**
     * User Id
     *
     * 所属用户ID
     */
    user_id: string
    /**
     * Aspect Id
     *
     * 图片比例ID
     */
    aspect_id: string
}

/**
 * ImageSearchResponse
 *
 * 图片搜索响应
 */
export interface ImageSearchResponse {
    /**
     * 图片分页结果
     */
    images: PageImageSimplePublic
    /**
     * Labels
     *
     * 图片标签列表
     */
    labels: Array<string>
}

/**
 * ImageSimplePublic
 *
 * 图片简略信息
 */
export interface ImageSimplePublic {
    /**
     * Id
     *
     * 图片ID
     */
    id: string
    /**
     * Name
     *
     * 图片名称
     */
    name: string
    /**
     * Description
     *
     * 图片描述
     */
    description: string
    /**
     * Labels
     *
     * 图片标签列表
     */
    labels: Array<string>
    /**
     * User Id
     *
     * 所属用户ID
     */
    user_id: string
}

/**
 * ImageUpdateRequest
 *
 * 图片更新请求
 */
export interface ImageUpdateRequest {
    /**
     * Name
     *
     * 图片名称
     */
    name?: string | null
    /**
     * Description
     *
     * 图片描述
     */
    description?: string | null
    /**
     * Visibility
     *
     * 图片可见性
     */
    visibility?: string | null
    /**
     * Labels
     *
     * 图片标签列表
     */
    labels?: Array<string> | null
}

/**
 * ImageVisibility
 */
export type ImageVisibility = -1 | 0 | 1

/**
 * OrderCreateRequest
 *
 * 订单创建请求
 */
export interface OrderCreateRequest {
    /**
     * Items
     *
     * 订单商品列表
     */
    items: Array<OrderItemCreateRequest>
    /**
     * Shipping Name
     *
     * 收件人姓名
     */
    shipping_name: string
    /**
     * Shipping Phone
     *
     * 收件人电话
     */
    shipping_phone: string
    /**
     * Shipping Address
     *
     * 收件人地址
     */
    shipping_address: string
}

/**
 * OrderItemCreateRequest
 *
 * 订单商品项创建请求
 */
export interface OrderItemCreateRequest {
    /**
     * Product Id
     *
     * 商品ID
     */
    product_id: string
    /**
     * Quantity
     *
     * 商品数量
     */
    quantity: number
}

/**
 * OrderItemPublic
 *
 * 订单商品项完整信息（包含商品具体信息）
 */
export interface OrderItemPublic {
    /**
     * Id
     *
     * 订单项ID
     */
    id: string
    /**
     * Quantity
     *
     * 商品数量
     */
    quantity: number
    /**
     * Unit Price
     *
     * 商品单价
     */
    unit_price: string
    /**
     * Total Price
     *
     * 商品总价
     */
    total_price: string
    /**
     * Product Id
     *
     * 商品ID
     */
    product_id: string
    /**
     * 商品信息
     */
    product: ProductPublic
}

/**
 * OrderPublic
 *
 * 订单完整信息（包含订单商品项具体信息）
 */
export interface OrderPublic {
    /**
     * Id
     *
     * 订单ID
     */
    id: string
    /**
     * 订单状态
     */
    status: OrderStatus
    /**
     * Product Money
     *
     * 商品金额
     */
    product_money: string
    /**
     * Shipping Money
     *
     * 运费金额
     */
    shipping_money: string
    /**
     * Payment Money
     *
     * 支付金额
     */
    payment_money: string
    /**
     * Shipping Name
     *
     * 收件人姓名
     */
    shipping_name: string
    /**
     * Shipping Phone
     *
     * 收件人电话
     */
    shipping_phone: string
    /**
     * Shipping Address
     *
     * 收件人地址
     */
    shipping_address: string
    /**
     * Shipping Sn
     *
     * 快递单号
     */
    shipping_sn: string | null
    /**
     * User Id
     *
     * 所属用户ID
     */
    user_id: string
    /**
     * Paid At
     *
     * 支付时间
     */
    paid_at: string | null
    /**
     * Shipped At
     *
     * 发货时间
     */
    shipped_at: string | null
    /**
     * Closed At
     *
     * 关闭时间
     */
    closed_at: string | null
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
    /**
     * Items
     *
     * 订单商品项列表
     */
    items: Array<OrderItemPublic>
}

/**
 * OrderSimplePublic
 *
 * 订单简略信息
 */
export interface OrderSimplePublic {
    /**
     * Id
     *
     * 订单ID
     */
    id: string
    /**
     * 订单状态
     */
    status: OrderStatus
    /**
     * Product Money
     *
     * 商品金额
     */
    product_money: string
    /**
     * Shipping Money
     *
     * 运费金额
     */
    shipping_money: string
    /**
     * Payment Money
     *
     * 支付金额
     */
    payment_money: string
    /**
     * Shipping Name
     *
     * 收件人姓名
     */
    shipping_name: string
    /**
     * Shipping Phone
     *
     * 收件人电话
     */
    shipping_phone: string
    /**
     * Shipping Address
     *
     * 收件人地址
     */
    shipping_address: string
    /**
     * Shipping Sn
     *
     * 快递单号
     */
    shipping_sn: string | null
    /**
     * User Id
     *
     * 所属用户ID
     */
    user_id: string
    /**
     * Paid At
     *
     * 支付时间
     */
    paid_at: string | null
    /**
     * Shipped At
     *
     * 发货时间
     */
    shipped_at: string | null
    /**
     * Closed At
     *
     * 关闭时间
     */
    closed_at: string | null
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * OrderStatus
 */
export type OrderStatus = -1 | 0 | 1 | 2 | 3 | 4

/**
 * OrderUpdateRequest
 *
 * 订单更新请求
 */
export interface OrderUpdateRequest {
    /**
     * Shipping Name
     *
     * 收件人姓名
     */
    shipping_name?: string | null
    /**
     * Shipping Phone
     *
     * 收件人电话
     */
    shipping_phone?: string | null
    /**
     * Shipping Address
     *
     * 收件人地址
     */
    shipping_address?: string | null
}

/**
 * Page[ArtifactManufacturerResponse]
 */
export interface PageArtifactManufacturerResponse {
    /**
     * Records
     */
    records: Array<ArtifactManufacturerResponse>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[BatchPublic]
 */
export interface PageBatchPublic {
    /**
     * Records
     */
    records: Array<BatchPublic>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[ImageSimplePublic]
 */
export interface PageImageSimplePublic {
    /**
     * Records
     */
    records: Array<ImageSimplePublic>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[OrderPublic]
 */
export interface PageOrderPublic {
    /**
     * Records
     */
    records: Array<OrderPublic>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * Page[ProductPublic]
 */
export interface PageProductPublic {
    /**
     * Records
     */
    records: Array<ProductPublic>
    /**
     * Total Row
     */
    total_row: number
    /**
     * Total Page
     */
    total_page: number
    /**
     * Page Number
     */
    page_number: number
    /**
     * Page Size
     */
    page_size: number
}

/**
 * ProductConsultRequest
 *
 * 商品咨询请求
 */
export interface ProductConsultRequest {
    /**
     * Design
     *
     * 商品设计JSON
     */
    design: {
        [key: string]: unknown
    }
    /**
     * Material Id
     *
     * 材料ID
     */
    material_id: string
    /**
     * Type Id
     *
     * 类型ID
     */
    type_id: string
}

/**
 * ProductConsultResponse
 *
 * 商品咨询响应
 */
export interface ProductConsultResponse {
    /**
     * Name
     *
     * 商品名称
     */
    name: string
    /**
     * Description
     *
     * 商品描述
     */
    description: string
    /**
     * Price
     *
     * 商品价格
     */
    price: string
}

/**
 * ProductCreateRequest
 *
 * 商品创建请求
 */
export interface ProductCreateRequest {
    /**
     * Name
     *
     * 商品名称
     */
    name?: string | null
    /**
     * Description
     *
     * 商品描述
     */
    description?: string | null
    /**
     * Design
     *
     * 商品设计JSON
     */
    design: {
        [key: string]: unknown
    }
    /**
     * Material Id
     *
     * 材料ID
     */
    material_id: string
    /**
     * Type Id
     *
     * 类型ID
     */
    type_id: string
}

/**
 * ProductMaterialPublic
 *
 * 材料公共信息
 */
export interface ProductMaterialPublic {
    /**
     * Id
     *
     * 材料ID
     */
    id: string
    /**
     * Name
     *
     * 材料名称
     */
    name: string
    /**
     * Description
     *
     * 材料描述
     */
    description: string
}

/**
 * ProductPublic
 *
 * 商品公共信息
 */
export interface ProductPublic {
    /**
     * Id
     *
     * 商品ID
     */
    id: string
    /**
     * Name
     *
     * 商品名称
     */
    name: string
    /**
     * Description
     *
     * 商品描述
     */
    description: string
    /**
     * Price
     *
     * 商品价格
     */
    price: string
    /**
     * Design
     *
     * 商品设计JSON
     */
    design: {
        [key: string]: unknown
    }
    /**
     * Is Modify Allowed
     *
     * 是否允许修改设计
     */
    is_modify_allowed: boolean
    /**
     * User Id
     *
     * 所属用户ID
     */
    user_id: string
    /**
     * 材料信息
     */
    material: ProductMaterialPublic
    /**
     * 类型信息
     */
    type: ProductTypePublic
    /**
     * Created At
     *
     * 创建时间
     */
    created_at: string
    /**
     * Updated At
     *
     * 更新时间
     */
    updated_at: string
}

/**
 * ProductSimpleResponse
 *
 * 商品简要信息
 */
export interface ProductSimpleResponse {
    /**
     * Id
     *
     * 商品ID
     */
    id: string
    /**
     * Design
     *
     * 商品设计JSON
     */
    design: {
        [key: string]: unknown
    }
    /**
     * 商品类型信息
     */
    type: ProductTypePublic
}

/**
 * ProductTypeDesign
 */
export type ProductTypeDesign = 0 | 1

/**
 * ProductTypeFunction
 */
export type ProductTypeFunction = 0

/**
 * ProductTypePublic
 *
 * 类型公共信息
 */
export interface ProductTypePublic {
    /**
     * Id
     *
     * 类型ID
     */
    id: string
    /**
     * Name
     *
     * 类型名称
     */
    name: string
    /**
     * Description
     *
     * 类型描述
     */
    description: string
    /**
     * 商品设计类型
     */
    design_type: ProductTypeDesign
    /**
     * Function Types
     *
     * 商品功能类型列表
     */
    function_types: Array<ProductTypeFunction>
}

/**
 * ProductUpdateRequest
 *
 * 商品更新请求
 */
export interface ProductUpdateRequest {
    /**
     * Name
     *
     * 商品名称
     */
    name?: string | null
    /**
     * Description
     *
     * 商品描述
     */
    description?: string | null
    /**
     * Design
     *
     * 商品设计JSON
     */
    design?: {
        [key: string]: unknown
    } | null
    /**
     * Material Id
     *
     * 材料ID
     */
    material_id?: string | null
    /**
     * Type Id
     *
     * 类型ID
     */
    type_id?: string | null
}

/**
 * UserAuthRequest
 *
 * 用户登录请求
 */
export interface UserAuthRequest {
    /**
     * Grant Type
     *
     * 授权类型
     */
    grant_type?: 'password' | 'refresh_token'
    /**
     * Username
     *
     * 用户名（仅在 grant_type 为 password 时需要）
     */
    username?: string | null
    /**
     * Password
     *
     * 密码（仅在 grant_type 为 password 时需要）
     */
    password?: string | null
    /**
     * 认证策略（仅在 grant_type 为 password 时需要）
     */
    strategy?: AuthStrategy | null
    /**
     * Refresh Token
     *
     * 刷新令牌（仅在 grant_type 为 refresh_token 时需要）
     */
    refresh_token?: string | null
}

/**
 * UserAuthResponse
 *
 * 用户令牌创建响应
 */
export interface UserAuthResponse {
    /**
     * Access Token
     *
     * 访问令牌
     */
    access_token: string
    /**
     * Refresh Token
     *
     * 刷新令牌
     */
    refresh_token: string
    /**
     * Token Type
     *
     * 令牌类型
     */
    token_type?: string
    /**
     * Expires In
     *
     * 令牌过期时间（秒）
     */
    expires_in: number
}

/**
 * UserCreateRequest
 *
 * 用户注册请求
 */
export interface UserCreateRequest {
    /**
     * Username
     *
     * 用户名
     */
    username: string
    /**
     * Password
     *
     * 密码
     */
    password: string
    /**
     * Email
     *
     * 邮箱
     */
    email: string
}

/**
 * UserMergeRequest
 *
 * 用户合并请求
 */
export interface UserMergeRequest {
    /**
     * Source Access Token
     *
     * 源用户的访问令牌
     */
    source_access_token: string
    /**
     * Target Access Token
     *
     * 目标用户的访问令牌
     */
    target_access_token: string
}

/**
 * UserPermission
 */
export type UserPermission = 'users:admin' | 'images:admin' | 'artifacts:admin'

/**
 * UserPublic
 *
 * 用户公共信息
 */
export interface UserPublic {
    /**
     * Id
     *
     * 用户ID
     */
    id: string
    /**
     * Username
     *
     * 用户名
     */
    username: string
    /**
     * Email
     *
     * 邮箱
     */
    email: string
    /**
     * Permissions
     *
     * 用户权限列表
     */
    permissions: Array<UserPermission>
}

/**
 * UserUpdateRequest
 *
 * 用户更新请求
 */
export interface UserUpdateRequest {
    /**
     * Username
     *
     * 用户名
     */
    username?: string | null
    /**
     * Password
     *
     * 密码
     */
    password?: string | null
    /**
     * Email
     *
     * 邮箱
     */
    email?: string | null
}

/**
 * ValidationError
 */
export interface ValidationError {
    /**
     * Location
     */
    loc: Array<string | number>
    /**
     * Message
     */
    msg: string
    /**
     * Error Type
     */
    type: string
}

/**
 * UsagiCardDXDesign
 *
 * 兔卡 DX 设计数据
 */
export interface UsagiCardDxDesign {
    /**
     * Game Version
     *
     * 游戏版本
     */
    game_version: string
    /**
     * Simplified Code
     *
     * 卡面标签
     */
    simplified_code: string
    /**
     * Character Name
     *
     * 立绘名称
     */
    character_name: string
    /**
     * Friend Code
     *
     * 好友代码
     */
    friend_code: string
    /**
     * Display Name
     *
     * 玩家名称
     */
    display_name: string
    /**
     * Dx Rating
     *
     * DX 分数
     */
    dx_rating: string
    /**
     * Qr Size
     *
     * 二维码大小
     */
    qr_size: number
    /**
     * Mask Type
     *
     * 遮罩类型
     */
    mask_type: number
    /**
     * Player Info Color
     *
     * 玩家信息颜色
     */
    player_info_color: string
    /**
     * Chara Info Color
     *
     * 角色信息颜色
     */
    chara_info_color: string
    /**
     * Show Qrcode Front
     *
     * 显示正面二维码
     */
    show_qrcode_front: boolean
    /**
     * Show Qrcode Back
     *
     * 显示反面二维码
     */
    show_qrcode_back: boolean
    /**
     * Show Dx Rating
     *
     * 显示 DX 分数
     */
    show_dx_rating: boolean
    /**
     * Show Display Name
     *
     * 显示玩家名称
     */
    show_display_name: boolean
    /**
     * Show Character Name
     *
     * 显示立绘名称
     */
    show_character_name: boolean
    /**
     * Show Friend Code
     *
     * 显示好友代码
     */
    show_friend_code: boolean
    /**
     * Enable Mask
     *
     * 启用遮罩
     */
    enable_mask: boolean
    /**
     * Character Id
     *
     * 立绘 ID
     */
    character_id: string
    /**
     * Mask Id
     *
     * 遮罩 ID
     */
    mask_id: string
    /**
     * Background Id
     *
     * 背景 ID
     */
    background_id: string
    /**
     * Cardback Id
     *
     * 卡背 ID
     */
    cardback_id: string
    /**
     * Frame Id
     *
     * 边框 ID
     */
    frame_id: string
    /**
     * Passname Id
     *
     * 通行证 ID
     */
    passname_id: string
}

/**
 * UsagiCardWarsDesign
 *
 * 兔卡 Wars 设计数据
 */
export interface UsagiCardWarsDesign {
    /**
     * Character Name
     *
     * 立绘名称
     */
    character_name: string
    /**
     * Skill Name
     *
     * 技能名称
     */
    skill_name: string
    /**
     * Skill Description
     *
     * 技能描述
     */
    skill_description: string
    /**
     * Miss
     *
     * MISS 值
     */
    miss: number
    /**
     * Combo
     *
     * COMBO 值
     */
    combo: number
    /**
     * Chain
     *
     * CHAIN 值
     */
    chain: number
    /**
     * Character Id
     *
     * 立绘 ID
     */
    character_id: string
    /**
     * Background Id
     *
     * 背景 ID
     */
    background_id: string
    /**
     * Cardback Id
     *
     * 卡背 ID
     */
    cardback_id: string
    /**
     * Frame Id
     *
     * 边框 ID
     */
    frame_id: string
    /**
     * Label Id
     *
     * 标签 ID
     */
    label_id: string
}

/**
 * UsagiCardStorage
 *
 * 兔卡存储数据
 */
export interface UsagiCardStorage {
    /**
     * Card Id
     */
    card_id: string
    /**
     * Activation Code
     */
    activation_code: string
}

export interface RootGetData {
    body?: never
    path?: never
    query?: never
    url: '/'
}

export interface RootGetResponses {
    /**
     * Successful Response
     */
    200: unknown
}

export interface GetArtifactsArtifactsGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Status
         *
         * 工件状态
         */
        status?: number | null
        /**
         * Product Id
         *
         * 所属商品ID
         */
        product_id?: string | null
        /**
         * Batch Id
         *
         * 所属批次ID
         */
        batch_id?: string | null
    }
    url: '/artifacts'
}

export interface GetArtifactsArtifactsGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetArtifactsArtifactsGetError = GetArtifactsArtifactsGetErrors[keyof GetArtifactsArtifactsGetErrors]

export interface GetArtifactsArtifactsGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageArtifactManufacturerResponse
}

export type GetArtifactsArtifactsGetResponse = GetArtifactsArtifactsGetResponses[keyof GetArtifactsArtifactsGetResponses]

export interface GetArtifactArtifactsArtifactIdGetData {
    body?: never
    path: {
        /**
         * Artifact Id
         */
        artifact_id: string
    }
    query?: never
    url: '/artifacts/{artifact_id}'
}

export interface GetArtifactArtifactsArtifactIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetArtifactArtifactsArtifactIdGetError = GetArtifactArtifactsArtifactIdGetErrors[keyof GetArtifactArtifactsArtifactIdGetErrors]

export interface GetArtifactArtifactsArtifactIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseArtifactUserResponse
}

export type GetArtifactArtifactsArtifactIdGetResponse = GetArtifactArtifactsArtifactIdGetResponses[keyof GetArtifactArtifactsArtifactIdGetResponses]

export interface UpdateArtifactStorageArtifactsArtifactIdStoragePatchData {
    body: ArtifactStorageUpdateRequest
    path: {
        /**
         * Artifact Id
         */
        artifact_id: string
    }
    query?: never
    url: '/artifacts/{artifact_id}/storage'
}

export interface UpdateArtifactStorageArtifactsArtifactIdStoragePatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateArtifactStorageArtifactsArtifactIdStoragePatchError = UpdateArtifactStorageArtifactsArtifactIdStoragePatchErrors[keyof UpdateArtifactStorageArtifactsArtifactIdStoragePatchErrors]

export interface UpdateArtifactStorageArtifactsArtifactIdStoragePatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseArtifactUserResponse
}

export type UpdateArtifactStorageArtifactsArtifactIdStoragePatchResponse = UpdateArtifactStorageArtifactsArtifactIdStoragePatchResponses[keyof UpdateArtifactStorageArtifactsArtifactIdStoragePatchResponses]

export interface UpdateArtifactStatusArtifactsArtifactIdStatusPatchData {
    body: ArtifactStatusUpdateRequest
    path: {
        /**
         * Artifact Id
         */
        artifact_id: string
    }
    query?: never
    url: '/artifacts/{artifact_id}/status'
}

export interface UpdateArtifactStatusArtifactsArtifactIdStatusPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateArtifactStatusArtifactsArtifactIdStatusPatchError = UpdateArtifactStatusArtifactsArtifactIdStatusPatchErrors[keyof UpdateArtifactStatusArtifactsArtifactIdStatusPatchErrors]

export interface UpdateArtifactStatusArtifactsArtifactIdStatusPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseArtifactManufacturerResponse
}

export type UpdateArtifactStatusArtifactsArtifactIdStatusPatchResponse = UpdateArtifactStatusArtifactsArtifactIdStatusPatchResponses[keyof UpdateArtifactStatusArtifactsArtifactIdStatusPatchResponses]

export interface GetBatchesBatchesGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Status
         *
         * 批次状态
         */
        status?: number | null
        /**
         * User Id
         *
         * 创建者用户ID
         */
        user_id?: string | null
    }
    url: '/batches'
}

export interface GetBatchesBatchesGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetBatchesBatchesGetError = GetBatchesBatchesGetErrors[keyof GetBatchesBatchesGetErrors]

export interface GetBatchesBatchesGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageBatchPublic
}

export type GetBatchesBatchesGetResponse = GetBatchesBatchesGetResponses[keyof GetBatchesBatchesGetResponses]

export interface CreateBatchBatchesPostData {
    body: BatchCreateRequest
    path?: never
    query?: never
    url: '/batches'
}

export interface CreateBatchBatchesPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreateBatchBatchesPostError = CreateBatchBatchesPostErrors[keyof CreateBatchBatchesPostErrors]

export interface CreateBatchBatchesPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseBatchPublic
}

export type CreateBatchBatchesPostResponse = CreateBatchBatchesPostResponses[keyof CreateBatchBatchesPostResponses]

export interface GetBatchBatchesBatchIdGetData {
    body?: never
    path: {
        /**
         * Batch Id
         */
        batch_id: string
    }
    query?: never
    url: '/batches/{batch_id}'
}

export interface GetBatchBatchesBatchIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetBatchBatchesBatchIdGetError = GetBatchBatchesBatchIdGetErrors[keyof GetBatchBatchesBatchIdGetErrors]

export interface GetBatchBatchesBatchIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseBatchPublic
}

export type GetBatchBatchesBatchIdGetResponse = GetBatchBatchesBatchIdGetResponses[keyof GetBatchBatchesBatchIdGetResponses]

export interface UpdateBatchBatchesBatchIdPatchData {
    body: BatchUpdateRequest
    path: {
        /**
         * Batch Id
         */
        batch_id: string
    }
    query?: never
    url: '/batches/{batch_id}'
}

export interface UpdateBatchBatchesBatchIdPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateBatchBatchesBatchIdPatchError = UpdateBatchBatchesBatchIdPatchErrors[keyof UpdateBatchBatchesBatchIdPatchErrors]

export interface UpdateBatchBatchesBatchIdPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseBatchPublic
}

export type UpdateBatchBatchesBatchIdPatchResponse = UpdateBatchBatchesBatchIdPatchResponses[keyof UpdateBatchBatchesBatchIdPatchResponses]

export interface GetImagesImagesGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Aspect Id
         *
         * 图片比例ID
         */
        aspect_id?: string | null
        /**
         * Visibility
         *
         * 图片可见性
         */
        visibility?: string | null
        /**
         * Original Id
         *
         * 图片元数据ID
         */
        original_id?: string | null
        /**
         * Labels
         *
         * 图片标签列表
         */
        labels?: Array<string> | null
        /**
         * Keyword
         *
         * 搜索关键词
         */
        keyword?: string | null
    }
    url: '/images'
}

export interface GetImagesImagesGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetImagesImagesGetError = GetImagesImagesGetErrors[keyof GetImagesImagesGetErrors]

export interface GetImagesImagesGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseImageSearchResponse
}

export type GetImagesImagesGetResponse = GetImagesImagesGetResponses[keyof GetImagesImagesGetResponses]

export interface CreateImageImagesPostData {
    body: BodyCreateImageImagesPost
    path?: never
    query?: never
    url: '/images'
}

export interface CreateImageImagesPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreateImageImagesPostError = CreateImageImagesPostErrors[keyof CreateImageImagesPostErrors]

export interface CreateImageImagesPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseImageSimplePublic
}

export type CreateImageImagesPostResponse = CreateImageImagesPostResponses[keyof CreateImageImagesPostResponses]

export interface DeleteImageImagesImageIdDeleteData {
    body?: never
    path: {
        /**
         * Image Id
         */
        image_id: string
    }
    query?: never
    url: '/images/{image_id}'
}

export interface DeleteImageImagesImageIdDeleteErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type DeleteImageImagesImageIdDeleteError = DeleteImageImagesImageIdDeleteErrors[keyof DeleteImageImagesImageIdDeleteErrors]

export interface DeleteImageImagesImageIdDeleteResponses {
    /**
     * Successful Response
     */
    200: AppResponseImageSimplePublic
}

export type DeleteImageImagesImageIdDeleteResponse = DeleteImageImagesImageIdDeleteResponses[keyof DeleteImageImagesImageIdDeleteResponses]

export interface GetImageImagesImageIdGetData {
    body?: never
    path: {
        /**
         * Image Id
         */
        image_id: string
    }
    query?: never
    url: '/images/{image_id}'
}

export interface GetImageImagesImageIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetImageImagesImageIdGetError = GetImageImagesImageIdGetErrors[keyof GetImageImagesImageIdGetErrors]

export interface GetImageImagesImageIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseImagePublic
}

export type GetImageImagesImageIdGetResponse = GetImageImagesImageIdGetResponses[keyof GetImageImagesImageIdGetResponses]

export interface UpdateImageImagesImageIdPatchData {
    body: ImageUpdateRequest
    path: {
        /**
         * Image Id
         */
        image_id: string
    }
    query?: never
    url: '/images/{image_id}'
}

export interface UpdateImageImagesImageIdPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateImageImagesImageIdPatchError = UpdateImageImagesImageIdPatchErrors[keyof UpdateImageImagesImageIdPatchErrors]

export interface UpdateImageImagesImageIdPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseImageSimplePublic
}

export type UpdateImageImagesImageIdPatchResponse = UpdateImageImagesImageIdPatchResponses[keyof UpdateImageImagesImageIdPatchResponses]

export interface GetImageAspectsImagesAspectsAspectIdGetData {
    body?: never
    path: {
        /**
         * Aspect Id
         */
        aspect_id: string
    }
    query?: never
    url: '/images/aspects/{aspect_id}'
}

export interface GetImageAspectsImagesAspectsAspectIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetImageAspectsImagesAspectsAspectIdGetError = GetImageAspectsImagesAspectsAspectIdGetErrors[keyof GetImageAspectsImagesAspectsAspectIdGetErrors]

export interface GetImageAspectsImagesAspectsAspectIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseImageAspectPublic
}

export type GetImageAspectsImagesAspectsAspectIdGetResponse = GetImageAspectsImagesAspectsAspectIdGetResponses[keyof GetImageAspectsImagesAspectsAspectIdGetResponses]

export interface GetOrdersOrdersGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Keyword
         *
         * 搜索关键词
         */
        keyword?: string | null
        /**
         * Status
         *
         * 订单状态
         */
        status?: OrderStatus | null
    }
    url: '/orders'
}

export interface GetOrdersOrdersGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetOrdersOrdersGetError = GetOrdersOrdersGetErrors[keyof GetOrdersOrdersGetErrors]

export interface GetOrdersOrdersGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageOrderPublic
}

export type GetOrdersOrdersGetResponse = GetOrdersOrdersGetResponses[keyof GetOrdersOrdersGetResponses]

export interface CreateOrderOrdersPostData {
    body: OrderCreateRequest
    path?: never
    query?: never
    url: '/orders'
}

export interface CreateOrderOrdersPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreateOrderOrdersPostError = CreateOrderOrdersPostErrors[keyof CreateOrderOrdersPostErrors]

export interface CreateOrderOrdersPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type CreateOrderOrdersPostResponse = CreateOrderOrdersPostResponses[keyof CreateOrderOrdersPostResponses]

export interface GetOrderOrdersOrderIdGetData {
    body?: never
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/orders/{order_id}'
}

export interface GetOrderOrdersOrderIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetOrderOrdersOrderIdGetError = GetOrderOrdersOrderIdGetErrors[keyof GetOrderOrdersOrderIdGetErrors]

export interface GetOrderOrdersOrderIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderPublic
}

export type GetOrderOrdersOrderIdGetResponse = GetOrderOrdersOrderIdGetResponses[keyof GetOrderOrdersOrderIdGetResponses]

export interface UpdateOrderOrdersOrderIdPatchData {
    body: OrderUpdateRequest
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/orders/{order_id}'
}

export interface UpdateOrderOrdersOrderIdPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateOrderOrdersOrderIdPatchError = UpdateOrderOrdersOrderIdPatchErrors[keyof UpdateOrderOrdersOrderIdPatchErrors]

export interface UpdateOrderOrdersOrderIdPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type UpdateOrderOrdersOrderIdPatchResponse = UpdateOrderOrdersOrderIdPatchResponses[keyof UpdateOrderOrdersOrderIdPatchResponses]

export interface CancelOrderOrdersOrderIdCancelPostData {
    body?: never
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/orders/{order_id}/cancel'
}

export interface CancelOrderOrdersOrderIdCancelPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CancelOrderOrdersOrderIdCancelPostError = CancelOrderOrdersOrderIdCancelPostErrors[keyof CancelOrderOrdersOrderIdCancelPostErrors]

export interface CancelOrderOrdersOrderIdCancelPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type CancelOrderOrdersOrderIdCancelPostResponse = CancelOrderOrdersOrderIdCancelPostResponses[keyof CancelOrderOrdersOrderIdCancelPostResponses]

export interface PayOrderOrdersOrderIdPayPostData {
    body?: never
    path: {
        /**
         * Order Id
         */
        order_id: string
    }
    query?: never
    url: '/orders/{order_id}/pay'
}

export interface PayOrderOrdersOrderIdPayPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type PayOrderOrdersOrderIdPayPostError = PayOrderOrdersOrderIdPayPostErrors[keyof PayOrderOrdersOrderIdPayPostErrors]

export interface PayOrderOrdersOrderIdPayPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseOrderSimplePublic
}

export type PayOrderOrdersOrderIdPayPostResponse = PayOrderOrdersOrderIdPayPostResponses[keyof PayOrderOrdersOrderIdPayPostResponses]

export interface GetProductsProductsGetData {
    body?: never
    path?: never
    query?: {
        /**
         * Page Number
         *
         * 页码
         */
        page_number?: number
        /**
         * Page Size
         *
         * 每页数量
         */
        page_size?: number
        /**
         * Keyword
         *
         * 搜索关键词
         */
        keyword?: string | null
        /**
         * User Id
         *
         * 所属用户ID
         */
        user_id?: string | null
        /**
         * Material Id
         *
         * 材料ID
         */
        material_id?: string | null
        /**
         * Type Id
         *
         * 类型ID
         */
        type_id?: string | null
    }
    url: '/products'
}

export interface GetProductsProductsGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetProductsProductsGetError = GetProductsProductsGetErrors[keyof GetProductsProductsGetErrors]

export interface GetProductsProductsGetResponses {
    /**
     * Successful Response
     */
    200: AppResponsePageProductPublic
}

export type GetProductsProductsGetResponse = GetProductsProductsGetResponses[keyof GetProductsProductsGetResponses]

export interface CreateProductProductsPostData {
    body: ProductCreateRequest
    path?: never
    query?: never
    url: '/products'
}

export interface CreateProductProductsPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreateProductProductsPostError = CreateProductProductsPostErrors[keyof CreateProductProductsPostErrors]

export interface CreateProductProductsPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseProductPublic
}

export type CreateProductProductsPostResponse = CreateProductProductsPostResponses[keyof CreateProductProductsPostResponses]

export interface GetProductProductsProductIdGetData {
    body?: never
    path: {
        /**
         * Product Id
         */
        product_id: string
    }
    query?: never
    url: '/products/{product_id}'
}

export interface GetProductProductsProductIdGetErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type GetProductProductsProductIdGetError = GetProductProductsProductIdGetErrors[keyof GetProductProductsProductIdGetErrors]

export interface GetProductProductsProductIdGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseProductPublic
}

export type GetProductProductsProductIdGetResponse = GetProductProductsProductIdGetResponses[keyof GetProductProductsProductIdGetResponses]

export interface UpdateProductProductsProductIdPatchData {
    body: ProductUpdateRequest
    path: {
        /**
         * Product Id
         */
        product_id: string
    }
    query?: never
    url: '/products/{product_id}'
}

export interface UpdateProductProductsProductIdPatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateProductProductsProductIdPatchError = UpdateProductProductsProductIdPatchErrors[keyof UpdateProductProductsProductIdPatchErrors]

export interface UpdateProductProductsProductIdPatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseProductPublic
}

export type UpdateProductProductsProductIdPatchResponse = UpdateProductProductsProductIdPatchResponses[keyof UpdateProductProductsProductIdPatchResponses]

export interface ConsultProductProductsConsultPostData {
    body: ProductConsultRequest
    path?: never
    query?: never
    url: '/products/consult'
}

export interface ConsultProductProductsConsultPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type ConsultProductProductsConsultPostError = ConsultProductProductsConsultPostErrors[keyof ConsultProductProductsConsultPostErrors]

export interface ConsultProductProductsConsultPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseProductConsultResponse
}

export type ConsultProductProductsConsultPostResponse = ConsultProductProductsConsultPostResponses[keyof ConsultProductProductsConsultPostResponses]

export interface RegisterAuthRegisterPostData {
    body: UserCreateRequest
    path?: never
    query?: never
    url: '/auth/register'
}

export interface RegisterAuthRegisterPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type RegisterAuthRegisterPostError = RegisterAuthRegisterPostErrors[keyof RegisterAuthRegisterPostErrors]

export interface RegisterAuthRegisterPostResponses {
    /**
     * Successful Response
     */
    200: AppResponseUserPublic
}

export type RegisterAuthRegisterPostResponse = RegisterAuthRegisterPostResponses[keyof RegisterAuthRegisterPostResponses]

export interface CreateTokenAuthTokenPostData {
    body: UserAuthRequest
    path?: never
    query?: never
    url: '/auth/token'
}

export interface CreateTokenAuthTokenPostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type CreateTokenAuthTokenPostError = CreateTokenAuthTokenPostErrors[keyof CreateTokenAuthTokenPostErrors]

export interface CreateTokenAuthTokenPostResponses {
    /**
     * Successful Response
     */
    200: UserAuthResponse
}

export type CreateTokenAuthTokenPostResponse = CreateTokenAuthTokenPostResponses[keyof CreateTokenAuthTokenPostResponses]

export interface GetCurrentUserUsersMeGetData {
    body?: never
    path?: never
    query?: never
    url: '/users/me'
}

export interface GetCurrentUserUsersMeGetResponses {
    /**
     * Successful Response
     */
    200: AppResponseUserPublic
}

export type GetCurrentUserUsersMeGetResponse = GetCurrentUserUsersMeGetResponses[keyof GetCurrentUserUsersMeGetResponses]

export interface UpdateCurrentUserUsersMePatchData {
    body: UserUpdateRequest
    path?: never
    query?: never
    url: '/users/me'
}

export interface UpdateCurrentUserUsersMePatchErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type UpdateCurrentUserUsersMePatchError = UpdateCurrentUserUsersMePatchErrors[keyof UpdateCurrentUserUsersMePatchErrors]

export interface UpdateCurrentUserUsersMePatchResponses {
    /**
     * Successful Response
     */
    200: AppResponseUserPublic
}

export type UpdateCurrentUserUsersMePatchResponse = UpdateCurrentUserUsersMePatchResponses[keyof UpdateCurrentUserUsersMePatchResponses]

export interface MergeUsersAuthMergePostData {
    body: UserMergeRequest
    path?: never
    query?: never
    url: '/auth/merge'
}

export interface MergeUsersAuthMergePostErrors {
    /**
     * Validation Error
     */
    422: HttpValidationError
}

export type MergeUsersAuthMergePostError = MergeUsersAuthMergePostErrors[keyof MergeUsersAuthMergePostErrors]

export interface MergeUsersAuthMergePostResponses {
    /**
     * Successful Response
     */
    200: AppResponseNoneType
}

export type MergeUsersAuthMergePostResponse = MergeUsersAuthMergePostResponses[keyof MergeUsersAuthMergePostResponses]
